---
name: Logging
path: Cisco-IOS-XR-um-logging-cfg:/logging
doc_category: Management
attributes:
  - yang_name: ipv4/dscp
    example: cs6
  - yang_name: trap
    example: informational
  - yang_name: Cisco-IOS-XR-um-logging-events-cfg:events/display-location
    example: true
  - yang_name: Cisco-IOS-XR-um-logging-events-cfg:events/level
    example: informational
  - yang_name: console
    example: disable
  - yang_name: monitor
    example: disable
  - yang_name: buffered/logging-buffer-size
    example: 4000000
  - yang_name: buffered/level
    example: debugging
  - yang_name: facility/level
    example: local7
  - yang_name: hostnameprefix
    example: HOSTNAME01
  - yang_name: suppress/duplicates
    example: true
