---
name: OC System Config
path: openconfig-system:/system/config
no_delete: true
ds_description: This data source can read the system configuration.
res_description: This resource can manage the system configuration.
doc_category: OpenConfig
attributes:
  - yang_name: hostname
    example: ROUTER-1
  - yang_name: domain-name
    example: cisco.com
    exclude_test: true
  - yang_name: login-banner
    example: My Login Banner
    exclude_test: true
  - yang_name: motd-banner
    example: My MOTD Banner
    exclude_test: true
