resource "iosxr_router_bgp_vrf" "example" {
  as_number = "65001"
  vrf_name  = "VRF1"
  mpls_activate_interfaces = [
    {
      interface_name = "GigabitEthernet0/0/0/1"
    }
  ]
  default_information_originate                    = true
  default_metric                                   = 125
  socket_receive_buffer_size                       = 1024
  socket_receive_buffer_size_read                  = 1024
  socket_send_buffer_size                          = 4096
  socket_send_buffer_size_write                    = 4096
  nexthop_mpls_forwarding_ibgp                     = true
  nexthop_resolution_allow_default                 = true
  timers_bgp_keepalive_interval                    = 0
  timers_bgp_holddown_zero                         = true
  timers_bgp_holddown_zero_minimum_acceptable_zero = true
  bgp_redistribute_internal                        = true
  bgp_router_id                                    = "22.22.22.22"
  bgp_unsafe_ebgp_policy                           = true
  bgp_auto_policy_soft_reset_disable               = true
  bgp_bestpath_cost_community_ignore               = true
  bgp_bestpath_compare_routerid                    = true
  bgp_bestpath_aigp_ignore                         = true
  bgp_bestpath_igp_metric_ignore                   = true
  bgp_bestpath_med_missing_as_worst                = true
  bgp_bestpath_as_path_ignore                      = true
  bgp_bestpath_as_path_multipath_relax             = true
  bgp_bestpath_origin_as_use_validity              = true
  bgp_bestpath_origin_as_allow_invalid             = true
  bgp_bestpath_sr_policy_prefer                    = true
  bgp_default_local_preference                     = 200
  bgp_enforce_first_as_disable                     = true
  bgp_fast_external_fallover_disable               = true
  bgp_log_neighbor_changes_disable                 = true
  bgp_log_message_disable                          = true
  bgp_multipath_use_cluster_list_length            = true
  bgp_origin_as_validation_signal_ibgp             = true
  bfd_minimum_interval                             = 10
  bfd_multiplier                                   = 4
  rd_auto                                          = true
  neighbors = [
    {
      address                             = "10.1.1.2"
      evpn_link_bandwidth                 = true
      evpn_link_bandwidth_per_path_number = 100
      remote_as                           = "65002"
      maximum_peers                       = 1000
      as_path_loopcheck_out               = "enable"
      advertisement_interval_seconds      = 10
      description                         = "My Neighbor Description"
      ignore_connected_check              = true
      ebgp_multihop_maximum_hop_count     = 10
      ebgp_multihop_mpls                  = true
      tcp_mss_value                       = 1460
      tcp_mtu_discovery                   = true
      bmp_activate_servers = [
        {
          server_number = 1
        }
      ]
      bfd_minimum_interval                                           = 10
      bfd_multiplier                                                 = 4
      bfd_fast_detect                                                = true
      bfd_fast_detect_strict_mode_negotiate_override                 = true
      local_as                                                       = "10"
      local_as_no_prepend_replace_as_dual_as                         = true
      password                                                       = "12341C2713181F13253920"
      password_inheritance_disable                                   = false
      receive_buffer_size                                            = 1024
      receive_buffer_size_read                                       = 1024
      send_buffer_size                                               = 4096
      send_buffer_size_write                                         = 4096
      fast_fallover                                                  = true
      shutdown                                                       = false
      timers_keepalive_interval                                      = 0
      timers_holddown_zero                                           = true
      timers_holddown_zero_minimum_acceptable_holdtime               = 30
      local_address                                                  = "192.168.1.1"
      log_neighbor_changes_detail                                    = true
      log_message_in_size                                            = 256
      log_message_out_size                                           = 256
      update_source                                                  = "GigabitEthernet0/0/0/1"
      dmz_link_bandwidth                                             = true
      ebgp_recv_extcommunity_dmz                                     = true
      ebgp_send_extcommunity_dmz_cumulative                          = true
      ttl_security                                                   = false
      session_open_mode                                              = "passive-only"
      dscp                                                           = "ef"
      capability_additional_paths_send                               = true
      capability_additional_paths_receive                            = true
      capability_suppress_all                                        = true
      capability_suppress_extended_nexthop_encoding                  = true
      capability_suppress_four_byte_as                               = true
      enforce_first_as                                               = "enable"
      idle_watch_time                                                = 240
      allowas_in                                                     = 3
      dampening                                                      = "enable"
      as_override                                                    = "enable"
      default_policy_action_in                                       = "reject"
      default_policy_action_out                                      = "reject"
      send_extended_community_ebgp                                   = true
      bestpath_origin_as_allow_invalid                               = true
      update_in_filtering_message_buffers                            = 10
      update_in_filtering_message_buffers_type                       = "non-circular"
      update_in_filtering_logging_disable                            = true
      update_in_filtering_attribute_filter_group                     = "GROUP1"
      update_in_labeled_unicast_equivalent                           = true
      update_in_error_handling_treat_as_withdraw                     = "enable"
      graceful_maintenance_activate                                  = true
      graceful_maintenance_local_preference                          = 200
      graceful_maintenance_as_prepends_number                        = 3
      graceful_maintenance_bandwidth_aware_percentage_threshold      = 75
      graceful_maintenance_bandwidth_aware_percentage_threshold_high = 80
    }
  ]
}
