// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceIosxrRouterIGMP(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "accounting_max_history", "30"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "nsf_lifetime", "300"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "dvmrp_enable", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "robustness_count", "5"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "maximum_groups", "50000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "maximum_groups_per_interface", "25000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "maximum_groups_per_interface_threshold", "20000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "maximum_groups_per_interface_acl", "IGMP_ACL"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "version", "3"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "query_interval", "125"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "query_timeout", "255"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "query_max_response_time", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "explicit_tracking", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "explicit_tracking_acl", "IGMP_ACL"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "access_group", "IGMP_ACL"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "ssm_map_statics.0.address", "10.1.1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "ssm_map_statics.0.access_list", "SSM_ACL"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "ssm_map_query_dns", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "missed_packets_gen_query", "5000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "missed_packets_grp_spec_query", "5000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "missed_packets_ssm_query", "5000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_router_igmp.test", "missed_packets_member_report", "5000"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxrRouterIGMPPrerequisitesConfig+testAccDataSourceIosxrRouterIGMPConfig(),
				Check: resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccDataSourceIosxrRouterIGMPPrerequisitesConfig = `
resource "iosxr_gnmi" "PreReq0" {
	path = "Cisco-IOS-XR-um-router-igmp-cfg:/router/igmp"
	attributes = {
	}
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceIosxrRouterIGMPConfig() string {
	config := `resource "iosxr_router_igmp" "test" {` + "\n"
	config += `	delete_mode = "attributes"` + "\n"
	config += `	accounting_max_history = 30` + "\n"
	config += `	nsf_lifetime = 300` + "\n"
	config += `	dvmrp_enable = true` + "\n"
	config += `	robustness_count = 5` + "\n"
	config += `	maximum_groups = 50000` + "\n"
	config += `	maximum_groups_per_interface = 25000` + "\n"
	config += `	maximum_groups_per_interface_threshold = 20000` + "\n"
	config += `	maximum_groups_per_interface_acl = "IGMP_ACL"` + "\n"
	config += `	version = 3` + "\n"
	config += `	query_interval = 125` + "\n"
	config += `	query_timeout = 255` + "\n"
	config += `	query_max_response_time = 10` + "\n"
	config += `	explicit_tracking = true` + "\n"
	config += `	explicit_tracking_acl = "IGMP_ACL"` + "\n"
	config += `	access_group = "IGMP_ACL"` + "\n"
	config += `	ssm_map_statics = [{` + "\n"
	config += `		address = "10.1.1.1"` + "\n"
	config += `		access_list = "SSM_ACL"` + "\n"
	config += `	}]` + "\n"
	config += `	ssm_map_query_dns = true` + "\n"
	config += `	missed_packets_gen_query = 5000` + "\n"
	config += `	missed_packets_grp_spec_query = 5000` + "\n"
	config += `	missed_packets_ssm_query = 5000` + "\n"
	config += `	missed_packets_member_report = 5000` + "\n"
	config += `	depends_on = [iosxr_gnmi.PreReq0, ]` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxr_router_igmp" "test" {
			depends_on = [iosxr_router_igmp.test]
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
