// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/tidwall/gjson"

	"github.com/CiscoDevNet/terraform-provider-iosxr/internal/provider/helpers"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &SegmentRoutingTEDataSource{}
	_ datasource.DataSourceWithConfigure = &SegmentRoutingTEDataSource{}
)

func NewSegmentRoutingTEDataSource() datasource.DataSource {
	return &SegmentRoutingTEDataSource{}
}

type SegmentRoutingTEDataSource struct {
	data *IosxrProviderData
}

func (d *SegmentRoutingTEDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_segment_routing_te"
}

func (d *SegmentRoutingTEDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Segment Routing TE configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the retrieved object.",
				Computed:            true,
			},
			"te_latency": schema.BoolAttribute{
				MarkdownDescription: "Use TE-latency algorithm",
				Computed:            true,
			},
			"max_install_standby_paths": schema.Int64Attribute{
				MarkdownDescription: "Allow additional candidate paths to warm up non forwarding LSPs",
				Computed:            true,
			},
			"kshortest_paths": schema.Int64Attribute{
				MarkdownDescription: "Maximum number of attempted paths for cumulative bounds (default 100)",
				Computed:            true,
			},
			"separate_next_hop": schema.BoolAttribute{
				MarkdownDescription: "Use Next Hop Separation in Forwarding",
				Computed:            true,
			},
			"maximum_sid_depth": schema.Int64Attribute{
				MarkdownDescription: "Maximum SID Depth Configuration",
				Computed:            true,
			},
			"effective_metric_admin_distance_metric_types": schema.ListNestedAttribute{
				MarkdownDescription: "Administrative distance advertised for this metric type",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"metric_type": schema.StringAttribute{
							MarkdownDescription: "MetricType",
							Computed:            true,
						},
						"admin_distance": schema.Int64Attribute{
							MarkdownDescription: "AdminDistance",
							Computed:            true,
						},
					},
				},
			},
			"effective_metric_admin_distance_flex_algo_metric_types": schema.ListNestedAttribute{
				MarkdownDescription: "Administrative distance advertised for this metric type",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"metric_type": schema.Int64Attribute{
							MarkdownDescription: "FlexAlgoMetricType",
							Computed:            true,
						},
						"admin_distance": schema.Int64Attribute{
							MarkdownDescription: "AdminDistance",
							Computed:            true,
						},
					},
				},
			},
			"steering_labeled_services_disable_on_demand_policies": schema.BoolAttribute{
				MarkdownDescription: "Disable steering for labeled services for on-demand policies",
				Computed:            true,
			},
			"steering_labeled_services_disable_all_policies": schema.BoolAttribute{
				MarkdownDescription: "Disable steering for labeled services for all policies",
				Computed:            true,
			},
			"steering_labeled_services_disable_pcep_policies": schema.BoolAttribute{
				MarkdownDescription: "Disable steering for labeled services for PCE initiated policies",
				Computed:            true,
			},
			"steering_labeled_services_disable_local_policies": schema.BoolAttribute{
				MarkdownDescription: "Disable steering for labeled services for local policies",
				Computed:            true,
			},
			"steering_labeled_services_disable_bgp_sr_te_policies": schema.BoolAttribute{
				MarkdownDescription: "Disable steering for labeled services for BGP-SRTE policies",
				Computed:            true,
			},
			"segment_lists_srv6_topology_check": schema.BoolAttribute{
				MarkdownDescription: "Enable topology check for all SRv6 segment-lists",
				Computed:            true,
			},
			"segment_lists_srv6_sid_format": schema.StringAttribute{
				MarkdownDescription: "Segment-lists configuration",
				Computed:            true,
			},
			"segment_lists_srv6_explicit_segments": schema.ListNestedAttribute{
				MarkdownDescription: "Segment-list configuration",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"path_name": schema.StringAttribute{
							MarkdownDescription: "Segment-list name",
							Computed:            true,
						},
						"srv6_segments": schema.ListNestedAttribute{
							MarkdownDescription: "SRv6 segment configuration for the given index",
							Computed:            true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"index": schema.Int64Attribute{
										MarkdownDescription: "Segment index",
										Computed:            true,
									},
									"address": schema.StringAttribute{
										MarkdownDescription: "IPv6 Address",
										Computed:            true,
									},
									"hop_type": schema.StringAttribute{
										MarkdownDescription: "SRv6 hop type",
										Computed:            true,
									},
								},
							},
						},
						"srv6_topology_check": schema.BoolAttribute{
							MarkdownDescription: "Enable Topology check for the given SRv6 segment-list",
							Computed:            true,
						},
					},
				},
			},
			"segment_lists_sr_mpls_explicit_segments": schema.ListNestedAttribute{
				MarkdownDescription: "Segment-list configuration",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"path_name": schema.StringAttribute{
							MarkdownDescription: "Segment-list name",
							Computed:            true,
						},
						"sr_mpls_segments": schema.ListNestedAttribute{
							MarkdownDescription: "Configure Segment/hop at the index",
							Computed:            true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"index": schema.Int64Attribute{
										MarkdownDescription: "Segment index",
										Computed:            true,
									},
									"type": schema.StringAttribute{
										MarkdownDescription: "Segment/hop type",
										Computed:            true,
									},
									"address": schema.StringAttribute{
										MarkdownDescription: "IP Address",
										Computed:            true,
									},
									"mpls_label": schema.Int64Attribute{
										MarkdownDescription: "MPLS Label",
										Computed:            true,
									},
									"adjacency_address": schema.StringAttribute{
										MarkdownDescription: "IP Adjacency Address",
										Computed:            true,
									},
									"address_type": schema.Int64Attribute{
										MarkdownDescription: "IP address types",
										Computed:            true,
									},
									"interface_identifier": schema.Int64Attribute{
										MarkdownDescription: "Interface Identifier",
										Computed:            true,
									},
									"prefix_length": schema.Int64Attribute{
										MarkdownDescription: "Prefix Length",
										Computed:            true,
									},
									"validate_flag": schema.Int64Attribute{
										MarkdownDescription: "Validate No Validate",
										Computed:            true,
									},
								},
							},
						},
					},
				},
			},
			"logging_pcep_peer_status": schema.BoolAttribute{
				MarkdownDescription: "Enable logging for pcep peer status",
				Computed:            true,
			},
			"logging_policy_status": schema.BoolAttribute{
				MarkdownDescription: "Enable logging for policy status",
				Computed:            true,
			},
			"cspf_cache_size": schema.Int64Attribute{
				MarkdownDescription: "Configure maximum size of the CSPF cache size in MiB",
				Computed:            true,
			},
			"timers_candidate_path_cleanup_delay": schema.Int64Attribute{
				MarkdownDescription: "Delay before cleaning up candidate paths",
				Computed:            true,
			},
			"timers_initial_verify_restart": schema.Int64Attribute{
				MarkdownDescription: "Timer to wait for topology convergence after topology starts populating for restart case",
				Computed:            true,
			},
			"timers_initial_verify_switchover": schema.Int64Attribute{
				MarkdownDescription: "Timer to wait for topology convergence after topology starts populating for switchover case",
				Computed:            true,
			},
			"timers_initial_verify_startup": schema.Int64Attribute{
				MarkdownDescription: "Timer to wait for topology convergence after topology starts populating for startup case",
				Computed:            true,
			},
			"timers_delete_delay": schema.Int64Attribute{
				MarkdownDescription: "Delete delay value in seconds",
				Computed:            true,
			},
			"timers_cleanup_delay": schema.Int64Attribute{
				MarkdownDescription: "Delay before cleaning up previous path",
				Computed:            true,
			},
			"timers_install_delay": schema.Int64Attribute{
				MarkdownDescription: "Delay before switching to a reoptimized path",
				Computed:            true,
			},
			"timers_periodic_reoptimization": schema.Int64Attribute{
				MarkdownDescription: "How often to perform periodic reoptimization of policies",
				Computed:            true,
			},
			"resource_lists": schema.ListNestedAttribute{
				MarkdownDescription: "Resource-list configuration",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"path_name": schema.StringAttribute{
							MarkdownDescription: "Resource-list name",
							Computed:            true,
						},
						"resources": schema.ListNestedAttribute{
							MarkdownDescription: "Configure Resource at the index",
							Computed:            true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"index": schema.Int64Attribute{
										MarkdownDescription: "Resource index",
										Computed:            true,
									},
									"type": schema.StringAttribute{
										MarkdownDescription: "Resource type",
										Computed:            true,
									},
									"address": schema.StringAttribute{
										MarkdownDescription: "IPv4 Address",
										Computed:            true,
									},
								},
							},
						},
					},
				},
			},
			"distribute_link_state": schema.BoolAttribute{
				MarkdownDescription: "Distribute policy information to BGP link-state",
				Computed:            true,
			},
			"distribute_link_state_throttle": schema.Int64Attribute{
				MarkdownDescription: "Set throttle update in seconds (default: 0 seconds)",
				Computed:            true,
			},
			"distribute_link_state_report_candidate_path_inactive": schema.BoolAttribute{
				MarkdownDescription: "Enable reporting of inactive candidate paths",
				Computed:            true,
			},
			"bfd_timers_session_bringup": schema.Int64Attribute{
				MarkdownDescription: "How long to wait for new BFD session to come up",
				Computed:            true,
			},
			"binding_sid_rules_explicit": schema.StringAttribute{
				MarkdownDescription: "Binding sid explicit rule",
				Computed:            true,
			},
			"binding_sid_rules_dynamic": schema.StringAttribute{
				MarkdownDescription: "Binding SID dynamic rule. Applicable for SR-MPLS and SRv6 policies",
				Computed:            true,
			},
			"interfaces": schema.ListNestedAttribute{
				MarkdownDescription: "SR-TE interface",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"interface_name": schema.StringAttribute{
							MarkdownDescription: "SR-TE Interface name",
							Computed:            true,
						},
						"affinities": schema.ListNestedAttribute{
							MarkdownDescription: "Set user defined interface attribute flags",
							Computed:            true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"affinity_name": schema.StringAttribute{
										MarkdownDescription: "Interface affinity names",
										Computed:            true,
									},
								},
							},
						},
						"metric": schema.Int64Attribute{
							MarkdownDescription: "Interface TE metric configuration",
							Computed:            true,
						},
					},
				},
			},
			"pce_peers_ipv4": schema.ListNestedAttribute{
				MarkdownDescription: "PCE peer",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"pce_address": schema.StringAttribute{
							MarkdownDescription: "Remote PCE address",
							Computed:            true,
						},
						"password_encrypted": schema.StringAttribute{
							MarkdownDescription: "PCC Peer MD5 Password",
							Computed:            true,
							Sensitive:           true,
						},
						"pce_group": schema.StringAttribute{
							MarkdownDescription: "Name of the PCE group - maximum 16 characters",
							Computed:            true,
						},
						"precedence": schema.Int64Attribute{
							MarkdownDescription: "Precedence value of this PCE",
							Computed:            true,
						},
						"tcp_ao_keychain": schema.StringAttribute{
							MarkdownDescription: "Name of the keychain",
							Computed:            true,
						},
						"tcp_ao_include_tcp_options": schema.BoolAttribute{
							MarkdownDescription: "Include other TCP options in the header",
							Computed:            true,
						},
					},
				},
			},
			"pce_peers_ipv6": schema.ListNestedAttribute{
				MarkdownDescription: "PCE peer",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"pce_address": schema.StringAttribute{
							MarkdownDescription: "Remote PCE address",
							Computed:            true,
						},
						"password_encrypted": schema.StringAttribute{
							MarkdownDescription: "PCC Peer MD5 Password",
							Computed:            true,
							Sensitive:           true,
						},
						"pce_group": schema.StringAttribute{
							MarkdownDescription: "Name of the PCE group - maximum 16 characters",
							Computed:            true,
						},
						"precedence": schema.Int64Attribute{
							MarkdownDescription: "Precedence value of this PCE",
							Computed:            true,
						},
						"tcp_ao_keychain": schema.StringAttribute{
							MarkdownDescription: "Name of the keychain",
							Computed:            true,
						},
						"tcp_ao_include_tcp_options": schema.BoolAttribute{
							MarkdownDescription: "Include other TCP options in the header",
							Computed:            true,
						},
					},
				},
			},
			"pcc_profiles": schema.ListNestedAttribute{
				MarkdownDescription: "Path profile configuration",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"profile_id": schema.Int64Attribute{
							MarkdownDescription: "Profile unique identifier",
							Computed:            true,
						},
						"steering_invalidation_drop": schema.BoolAttribute{
							MarkdownDescription: "Enable path invalidation drop",
							Computed:            true,
						},
						"auto_route_include_all_ipv4": schema.BoolAttribute{
							MarkdownDescription: "Include all IPv4 prefixes to autoroute",
							Computed:            true,
						},
						"auto_route_include_all_ipv6": schema.BoolAttribute{
							MarkdownDescription: "Include all eligible IPv6 prefixes",
							Computed:            true,
						},
						"auto_route_force_sr_include": schema.BoolAttribute{
							MarkdownDescription: "Force SR traffic over autoroute policy",
							Computed:            true,
						},
						"auto_route_forward_class": schema.Int64Attribute{
							MarkdownDescription: "Forward class associated with the policy",
							Computed:            true,
						},
						"auto_route_metric_type": schema.StringAttribute{
							MarkdownDescription: "Metric type",
							Computed:            true,
						},
						"auto_route_metric_relative_value": schema.Int64Attribute{
							MarkdownDescription: "Autoroute relative metric",
							Computed:            true,
						},
						"auto_route_metric_constant_value": schema.Int64Attribute{
							MarkdownDescription: "Autoroute constant metric",
							Computed:            true,
						},
					},
				},
			},
			"pcc_redundancy_pcc_centric": schema.BoolAttribute{
				MarkdownDescription: "Enable PCC centric model, where PCC only allows the lowest precedence PCE to initiate policies. THIS COMMAND IS DEPRECATED",
				Computed:            true,
			},
			"pcc_redundancy_pce_centric": schema.BoolAttribute{
				MarkdownDescription: "Enable PCE centric model",
				Computed:            true,
			},
			"pcc_dead_timer": schema.Int64Attribute{
				MarkdownDescription: "Amount of time after which the peer can declare this session down, if no PCEP message has been received",
				Computed:            true,
			},
			"pcc_keepalive_timer": schema.Int64Attribute{
				MarkdownDescription: "Maximum time between two consecutive PCEP messages sent by this node",
				Computed:            true,
			},
			"pcc_initiated_state": schema.Int64Attribute{
				MarkdownDescription: "Amount of time that PCE initiated policy can exist as an orphan before it is cleaned up",
				Computed:            true,
			},
			"pcc_initiated_orphan": schema.Int64Attribute{
				MarkdownDescription: "Amount of time that PCE initiated policy remains delegated to a peer that has gone down",
				Computed:            true,
			},
			"pcc_delegation_timeout": schema.Int64Attribute{
				MarkdownDescription: "Maximum time delegated SR-TE policies can remain up without an active connection to a PCE",
				Computed:            true,
			},
			"pcc_report_all": schema.BoolAttribute{
				MarkdownDescription: "Report all local SR policies to connected PCEP peers",
				Computed:            true,
			},
			"pcc_source_address_ipv4": schema.StringAttribute{
				MarkdownDescription: "Local source IP address to use on PCEP sessions",
				Computed:            true,
			},
			"pcc_source_address_ipv6": schema.StringAttribute{
				MarkdownDescription: "Local source IP address to use on PCEP sessions",
				Computed:            true,
			},
			"traces": schema.ListNestedAttribute{
				MarkdownDescription: "Trace count for provided buffer",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"buffer_name": schema.StringAttribute{
							MarkdownDescription: "Buffer name",
							Computed:            true,
						},
						"trace_count": schema.Int64Attribute{
							MarkdownDescription: "Trace count",
							Computed:            true,
						},
					},
				},
			},
			"path_disable_algo_checks_strict_spf_areas": schema.ListNestedAttribute{
				MarkdownDescription: "IGP area",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"area_id": schema.Int64Attribute{
							MarkdownDescription: "Area identifier",
							Computed:            true,
						},
						"protocol": schema.StringAttribute{
							MarkdownDescription: "IGP protocol",
							Computed:            true,
						},
					},
				},
			},
			"path_disable_algo_checks_strict_spf_all_areas": schema.BoolAttribute{
				MarkdownDescription: "Disable check for all IGP areas",
				Computed:            true,
			},
			"affinity_maps": schema.ListNestedAttribute{
				MarkdownDescription: "Affinity-map entry",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"affinity_name": schema.StringAttribute{
							MarkdownDescription: "Affinity-map bit-position",
							Computed:            true,
						},
						"bit_position": schema.Int64Attribute{
							MarkdownDescription: "Affinity-map bit-position",
							Computed:            true,
						},
					},
				},
			},
			"candidate_paths": schema.ListNestedAttribute{
				MarkdownDescription: "Configurations for candidate paths of specific type.",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"path_type": schema.StringAttribute{
							MarkdownDescription: "Candidate-path type",
							Computed:            true,
						},
						"source_address_selection": schema.BoolAttribute{
							MarkdownDescription: "True only",
							Computed:            true,
						},
						"source_address_type": schema.StringAttribute{
							MarkdownDescription: "IP address type",
							Computed:            true,
						},
						"source_address": schema.StringAttribute{
							MarkdownDescription: "Source address",
							Computed:            true,
						},
					},
				},
			},
			"srv6_locator": schema.StringAttribute{
				MarkdownDescription: "SRv6 locator name",
				Computed:            true,
			},
			"srv6_locator_binding_sid_type": schema.StringAttribute{
				MarkdownDescription: "Binding Segment ID type",
				Computed:            true,
			},
			"srv6_locator_behavior": schema.StringAttribute{
				MarkdownDescription: "SRv6 USID Behavior",
				Computed:            true,
			},
			"srv6_maximum_sid_depth": schema.Int64Attribute{
				MarkdownDescription: "SRv6 Maximum SID Depth Configuration",
				Computed:            true,
			},
		},
	}
}

func (d *SegmentRoutingTEDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.data = req.ProviderData.(*IosxrProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (d *SegmentRoutingTEDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config SegmentRoutingTEData

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	device, ok := d.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", config.Device.ValueString()))
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	if device.Managed {
		if device.Protocol == "gnmi" {
			if !d.data.ReuseConnection {
				defer device.GnmiClient.Disconnect()
			}
			getResp, err := device.GnmiClient.Get(ctx, []string{config.getPath()})
			if err != nil {
				resp.Diagnostics.AddError("Unable to apply gNMI Get operation", err.Error())
				return
			}

			// Defensive bounds checking for response structure
			if len(getResp.Notifications) == 0 {
				resp.Diagnostics.AddError("Invalid gNMI response",
					"Response contains no notifications")
				return
			}
			if len(getResp.Notifications[0].Update) == 0 {
				resp.Diagnostics.AddError("Invalid gNMI response",
					"Response notification contains no updates")
				return
			}

			respBody := getResp.Notifications[0].Update[0].Val.GetJsonIetfVal()
			config.fromBody(ctx, gjson.ParseBytes(respBody))
		} else {
			// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
			locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
			if locked {
				defer device.NetconfOpMutex.Unlock()
			}
			defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

			filter := helpers.GetSubtreeFilter(config.getXPath())
			res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
			if err != nil {
				resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", config.getPath(), err))
				return
			}

			config.fromBodyXML(ctx, res.Res)
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
