// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceIosxrL2VPNXconnectGroupP2P(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_l2vpn_xconnect_group_p2p.test", "description", "My P2P Description"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_l2vpn_xconnect_group_p2p.test", "interfaces.0.interface_name", "GigabitEthernet0/0/0/2"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_l2vpn_xconnect_group_p2p.test", "neighbor_evpn_evi_segment_routing_services.0.vpn_id", "4600"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_l2vpn_xconnect_group_p2p.test", "neighbor_evpn_evi_segment_routing_services.0.service_id", "600"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_l2vpn_xconnect_group_p2p.test", "neighbor_evpn_evi_segment_routing_services.0.segment_routing_srv6_locator", "LOC11"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxrL2VPNXconnectGroupP2PConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

func testAccDataSourceIosxrL2VPNXconnectGroupP2PConfig() string {
	config := `resource "iosxr_l2vpn_xconnect_group_p2p" "test" {` + "\n"
	config += `	delete_mode = "attributes"` + "\n"
	config += `	group_name = "P2P"` + "\n"
	config += `	p2p_xconnect_name = "XC"` + "\n"
	config += `	description = "My P2P Description"` + "\n"
	config += `	interfaces = [{` + "\n"
	config += `		interface_name = "GigabitEthernet0/0/0/2"` + "\n"
	config += `	}]` + "\n"
	config += `	neighbor_evpn_evi_segment_routing_services = [{` + "\n"
	config += `		vpn_id = 4600` + "\n"
	config += `		service_id = 600` + "\n"
	config += `		segment_routing_srv6_locator = "LOC11"` + "\n"
	config += `	}]` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxr_l2vpn_xconnect_group_p2p" "test" {
			group_name = "P2P"
			p2p_xconnect_name = "XC"
			depends_on = [iosxr_l2vpn_xconnect_group_p2p.test]
		}
	`
	return config
}
