// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceIosxrBanner(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxr_banner.test", "line", " Hello user !"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxrBannerConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

func testAccDataSourceIosxrBannerConfig() string {
	config := `resource "iosxr_banner" "test" {` + "\n"
	config += `	banner_type = "login"` + "\n"
	config += `	line = " Hello user !"` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxr_banner" "test" {
			banner_type = "login"
			depends_on = [iosxr_banner.test]
		}
	`
	return config
}
