// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

type dataSourceRouterBGPAddressFamilyRedistributeISISType struct{}

func (t dataSourceRouterBGPAddressFamilyRedistributeISISType) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Router BGP Address Family Redistribute ISIS configuration.",

		Attributes: map[string]tfsdk.Attribute{
			"device": {
				MarkdownDescription: "A device name from the provider configuration.",
				Type:                types.StringType,
				Optional:            true,
			},
			"id": {
				MarkdownDescription: "The path of the retrieved object.",
				Type:                types.StringType,
				Computed:            true,
			},
			"as_number": {
				MarkdownDescription: "bgp as-number",
				Type:                types.StringType,
				Required:            true,
			},
			"af_name": {
				MarkdownDescription: "Enter Address Family command mode",
				Type:                types.StringType,
				Required:            true,
			},
			"instance_name": {
				MarkdownDescription: "ISO IS-IS",
				Type:                types.StringType,
				Required:            true,
			},
			"level_one": {
				MarkdownDescription: "Redistribute ISIS level 1 routes",
				Type:                types.BoolType,
				Computed:            true,
			},
			"level_one_two": {
				MarkdownDescription: "Redistribute ISIS level 2 ISIS routes",
				Type:                types.BoolType,
				Computed:            true,
			},
			"level_one_two_one_inter_area": {
				MarkdownDescription: "Redistribute ISIS level 1 inter-area routes",
				Type:                types.BoolType,
				Computed:            true,
			},
			"level_one_one_inter_area": {
				MarkdownDescription: "Redistribute ISIS level 1 inter-area routes",
				Type:                types.BoolType,
				Computed:            true,
			},
			"level_two": {
				MarkdownDescription: "Redistribute ISIS level 2 ISIS routes",
				Type:                types.BoolType,
				Computed:            true,
			},
			"level_two_one_inter_area": {
				MarkdownDescription: "Redistribute ISIS level 1 inter-area routes",
				Type:                types.BoolType,
				Computed:            true,
			},
			"level_one_inter_area": {
				MarkdownDescription: "Redistribute ISIS level 1 inter-area routes",
				Type:                types.BoolType,
				Computed:            true,
			},
			"metric": {
				MarkdownDescription: "Metric for redistributed routes",
				Type:                types.Int64Type,
				Computed:            true,
			},
		},
	}, nil
}

func (t dataSourceRouterBGPAddressFamilyRedistributeISISType) NewDataSource(ctx context.Context, in tfsdk.Provider) (tfsdk.DataSource, diag.Diagnostics) {
	provider, diags := convertProviderType(in)

	return dataSourceRouterBGPAddressFamilyRedistributeISIS{
		provider: provider,
	}, diags
}

type dataSourceRouterBGPAddressFamilyRedistributeISIS struct {
	provider provider
}

func (d dataSourceRouterBGPAddressFamilyRedistributeISIS) Read(ctx context.Context, req tfsdk.ReadDataSourceRequest, resp *tfsdk.ReadDataSourceResponse) {
	var config RouterBGPAddressFamilyRedistributeISIS

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	getResp, diags := d.provider.client.Get(ctx, config.Device.Value, config.getPath())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	config.fromBody(getResp.Notification[0].Update[0].Val.GetJsonIetfVal())
	config.Id = types.String{Value: config.getPath()}

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}
