// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"path"
	"reflect"
	"strconv"
	"strings"

	"github.com/CiscoDevNet/terraform-provider-iosxr/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type SegmentRoutingV6 struct {
	Device                            types.String               `tfsdk:"device"`
	Id                                types.String               `tfsdk:"id"`
	DeleteMode                        types.String               `tfsdk:"delete_mode"`
	Enable                            types.Bool                 `tfsdk:"enable"`
	SidHoldtime                       types.Int64                `tfsdk:"sid_holdtime"`
	LoggingLocatorStatus              types.Bool                 `tfsdk:"logging_locator_status"`
	Formats                           []SegmentRoutingV6Formats  `tfsdk:"formats"`
	Locators                          []SegmentRoutingV6Locators `tfsdk:"locators"`
	EncapsulationTrafficClassOption   types.String               `tfsdk:"encapsulation_traffic_class_option"`
	EncapsulationTrafficClassValue    types.Int64                `tfsdk:"encapsulation_traffic_class_value"`
	EncapsulationHopLimitOption       types.String               `tfsdk:"encapsulation_hop_limit_option"`
	EncapsulationHopLimitValue        types.Int64                `tfsdk:"encapsulation_hop_limit_value"`
	EncapsulationSourceAddress        types.String               `tfsdk:"encapsulation_source_address"`
	EncapsulationSourceAddressOption  types.String               `tfsdk:"encapsulation_source_address_option"`
	EncapsulationSourceAddressAddress types.String               `tfsdk:"encapsulation_source_address_address"`
}

type SegmentRoutingV6Data struct {
	Device                            types.String               `tfsdk:"device"`
	Id                                types.String               `tfsdk:"id"`
	Enable                            types.Bool                 `tfsdk:"enable"`
	SidHoldtime                       types.Int64                `tfsdk:"sid_holdtime"`
	LoggingLocatorStatus              types.Bool                 `tfsdk:"logging_locator_status"`
	Formats                           []SegmentRoutingV6Formats  `tfsdk:"formats"`
	Locators                          []SegmentRoutingV6Locators `tfsdk:"locators"`
	EncapsulationTrafficClassOption   types.String               `tfsdk:"encapsulation_traffic_class_option"`
	EncapsulationTrafficClassValue    types.Int64                `tfsdk:"encapsulation_traffic_class_value"`
	EncapsulationHopLimitOption       types.String               `tfsdk:"encapsulation_hop_limit_option"`
	EncapsulationHopLimitValue        types.Int64                `tfsdk:"encapsulation_hop_limit_value"`
	EncapsulationSourceAddress        types.String               `tfsdk:"encapsulation_source_address"`
	EncapsulationSourceAddressOption  types.String               `tfsdk:"encapsulation_source_address_option"`
	EncapsulationSourceAddressAddress types.String               `tfsdk:"encapsulation_source_address_address"`
}
type SegmentRoutingV6Formats struct {
	Name                                  types.String `tfsdk:"name"`
	FormatEnable                          types.Bool   `tfsdk:"format_enable"`
	UsidLocalIdBlockRangesLibStart        types.Int64  `tfsdk:"usid_local_id_block_ranges_lib_start"`
	UsidLocalIdBlockRangesExplictLibStart types.Int64  `tfsdk:"usid_local_id_block_ranges_explict_lib_start"`
	UsidWideLocalIdBlockExplicitRange     types.Int64  `tfsdk:"usid_wide_local_id_block_explicit_range"`
}
type SegmentRoutingV6Locators struct {
	LocatorEnable        types.Bool   `tfsdk:"locator_enable"`
	Name                 types.String `tfsdk:"name"`
	MicroSegmentBehavior types.String `tfsdk:"micro_segment_behavior"`
	Prefix               types.String `tfsdk:"prefix"`
	PrefixLength         types.Int64  `tfsdk:"prefix_length"`
	Anycast              types.Bool   `tfsdk:"anycast"`
	Algorithm            types.Int64  `tfsdk:"algorithm"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data SegmentRoutingV6) getPath() string {
	return "Cisco-IOS-XR-segment-routing-ms-cfg:/sr/Cisco-IOS-XR-segment-routing-srv6-cfg:srv6"
}

func (data SegmentRoutingV6Data) getPath() string {
	return "Cisco-IOS-XR-segment-routing-ms-cfg:/sr/Cisco-IOS-XR-segment-routing-srv6-cfg:srv6"
}

// getXPath returns the XPath for NETCONF operations
func (data SegmentRoutingV6) getXPath() string {
	path := "Cisco-IOS-XR-segment-routing-ms-cfg:/sr/Cisco-IOS-XR-segment-routing-srv6-cfg:srv6"
	return path
}

func (data SegmentRoutingV6Data) getXPath() string {
	path := "Cisco-IOS-XR-segment-routing-ms-cfg:/sr/Cisco-IOS-XR-segment-routing-srv6-cfg:srv6"
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data SegmentRoutingV6) toBody(ctx context.Context, providerVersion string) string {
	body := "{}"
	if !data.Enable.IsNull() && !data.Enable.IsUnknown() {
		if data.Enable.ValueBool() {
			body, _ = sjson.Set(body, "enable", []interface{}{nil})
		}
	}
	if !data.SidHoldtime.IsNull() && !data.SidHoldtime.IsUnknown() {
		body, _ = sjson.Set(body, "sid-holdtime", strconv.FormatInt(data.SidHoldtime.ValueInt64(), 10))
	}
	if !data.LoggingLocatorStatus.IsNull() && !data.LoggingLocatorStatus.IsUnknown() {
		if data.LoggingLocatorStatus.ValueBool() {
			body, _ = sjson.Set(body, "logging.locator-status", []interface{}{nil})
		}
	}
	if !data.EncapsulationTrafficClassOption.IsNull() && !data.EncapsulationTrafficClassOption.IsUnknown() {
		body, _ = sjson.Set(body, "encapsulation.traffic-class.option", data.EncapsulationTrafficClassOption.ValueString())
	}
	if !data.EncapsulationTrafficClassValue.IsNull() && !data.EncapsulationTrafficClassValue.IsUnknown() {
		body, _ = sjson.Set(body, "encapsulation.traffic-class.value", strconv.FormatInt(data.EncapsulationTrafficClassValue.ValueInt64(), 10))
	}
	if !data.EncapsulationHopLimitOption.IsNull() && !data.EncapsulationHopLimitOption.IsUnknown() {
		body, _ = sjson.Set(body, "encapsulation.hop-limit.option", data.EncapsulationHopLimitOption.ValueString())
	}
	if !data.EncapsulationHopLimitValue.IsNull() && !data.EncapsulationHopLimitValue.IsUnknown() {
		body, _ = sjson.Set(body, "encapsulation.hop-limit.value", strconv.FormatInt(data.EncapsulationHopLimitValue.ValueInt64(), 10))
	}
	if providerVersion == "" || !helpers.VersionAtLeast(providerVersion, "26.2") {
		if !data.EncapsulationSourceAddress.IsNull() && !data.EncapsulationSourceAddress.IsUnknown() {
			body, _ = sjson.Set(body, "encapsulation.source-address", data.EncapsulationSourceAddress.ValueString())
		}
	}
	if helpers.VersionAtLeast(providerVersion, "26.2") {
		if !data.EncapsulationSourceAddressOption.IsNull() && !data.EncapsulationSourceAddressOption.IsUnknown() {
			body, _ = sjson.Set(body, "encapsulation.source-address.option", data.EncapsulationSourceAddressOption.ValueString())
		}
	}
	if helpers.VersionAtLeast(providerVersion, "26.2") {
		if !data.EncapsulationSourceAddressAddress.IsNull() && !data.EncapsulationSourceAddressAddress.IsUnknown() {
			body, _ = sjson.Set(body, "encapsulation.source-address.address", data.EncapsulationSourceAddressAddress.ValueString())
		}
	}
	if len(data.Formats) > 0 {
		body, _ = sjson.Set(body, "formats.formats.format", []interface{}{})
		for index, item := range data.Formats {
			if !item.Name.IsNull() && !item.Name.IsUnknown() {
				body, _ = sjson.Set(body, "formats.formats.format"+"."+strconv.Itoa(index)+"."+"name", item.Name.ValueString())
			}
			if !item.FormatEnable.IsNull() && !item.FormatEnable.IsUnknown() {
				if item.FormatEnable.ValueBool() {
					body, _ = sjson.Set(body, "formats.formats.format"+"."+strconv.Itoa(index)+"."+"format-enable", []interface{}{nil})
				}
			}
			if !item.UsidLocalIdBlockRangesLibStart.IsNull() && !item.UsidLocalIdBlockRangesLibStart.IsUnknown() {
				body, _ = sjson.Set(body, "formats.formats.format"+"."+strconv.Itoa(index)+"."+"usid.local-id-block-ranges.lib-start", strconv.FormatInt(item.UsidLocalIdBlockRangesLibStart.ValueInt64(), 10))
			}
			if !item.UsidLocalIdBlockRangesExplictLibStart.IsNull() && !item.UsidLocalIdBlockRangesExplictLibStart.IsUnknown() {
				body, _ = sjson.Set(body, "formats.formats.format"+"."+strconv.Itoa(index)+"."+"usid.local-id-block-ranges.explict-lib-start", strconv.FormatInt(item.UsidLocalIdBlockRangesExplictLibStart.ValueInt64(), 10))
			}
			if !item.UsidWideLocalIdBlockExplicitRange.IsNull() && !item.UsidWideLocalIdBlockExplicitRange.IsUnknown() {
				body, _ = sjson.Set(body, "formats.formats.format"+"."+strconv.Itoa(index)+"."+"usid.wide-local-id-block-explicit-range", strconv.FormatInt(item.UsidWideLocalIdBlockExplicitRange.ValueInt64(), 10))
			}
		}
	}
	if len(data.Locators) > 0 {
		body, _ = sjson.Set(body, "locators.locators.locator", []interface{}{})
		for index, item := range data.Locators {
			if !item.LocatorEnable.IsNull() && !item.LocatorEnable.IsUnknown() {
				if item.LocatorEnable.ValueBool() {
					body, _ = sjson.Set(body, "locators.locators.locator"+"."+strconv.Itoa(index)+"."+"locator-enable", []interface{}{nil})
				}
			}
			if !item.Name.IsNull() && !item.Name.IsUnknown() {
				body, _ = sjson.Set(body, "locators.locators.locator"+"."+strconv.Itoa(index)+"."+"name", item.Name.ValueString())
			}
			if !item.MicroSegmentBehavior.IsNull() && !item.MicroSegmentBehavior.IsUnknown() {
				body, _ = sjson.Set(body, "locators.locators.locator"+"."+strconv.Itoa(index)+"."+"micro-segment.behavior", item.MicroSegmentBehavior.ValueString())
			}
			if !item.Prefix.IsNull() && !item.Prefix.IsUnknown() {
				body, _ = sjson.Set(body, "locators.locators.locator"+"."+strconv.Itoa(index)+"."+"prefix.prefix", item.Prefix.ValueString())
			}
			if !item.PrefixLength.IsNull() && !item.PrefixLength.IsUnknown() {
				body, _ = sjson.Set(body, "locators.locators.locator"+"."+strconv.Itoa(index)+"."+"prefix.prefix-length", strconv.FormatInt(item.PrefixLength.ValueInt64(), 10))
			}
			if !item.Anycast.IsNull() && !item.Anycast.IsUnknown() {
				if item.Anycast.ValueBool() {
					body, _ = sjson.Set(body, "locators.locators.locator"+"."+strconv.Itoa(index)+"."+"anycast", []interface{}{nil})
				}
			}
			if !item.Algorithm.IsNull() && !item.Algorithm.IsUnknown() {
				body, _ = sjson.Set(body, "locators.locators.locator"+"."+strconv.Itoa(index)+"."+"algorithm", strconv.FormatInt(item.Algorithm.ValueInt64(), 10))
			}
		}
	}
	return body
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin getVersionConstraints

// GetVersionConstraints returns the version constraints for all fields
func (data SegmentRoutingV6) GetVersionConstraints() []helpers.FieldVersionConstraint {
	constraints := make([]helpers.FieldVersionConstraint, 0)

	constraints = append(constraints, []helpers.FieldVersionConstraint{
		{
			FieldPath: "encapsulation_source_address",

			RemovedInVersion: "26.2",
		},
		{
			FieldPath:      "encapsulation_source_address_option",
			AddedInVersion: "26.2",
		},
		{
			FieldPath:      "encapsulation_source_address_address",
			AddedInVersion: "26.2",
		},
	}...)
	if len(constraints) == 0 {
		return nil
	}
	return constraints
}

// End of section. //template:end getVersionConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getRangeConstraints

// GetRangeConstraints returns the version-specific range constraints for integer fields
func (data SegmentRoutingV6) GetRangeConstraints() []helpers.FieldRangeConstraint {
	return nil
}

// End of section. //template:end getRangeConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getEnumConstraints

// GetEnumConstraints returns the version-specific enum constraints for string fields
func (data SegmentRoutingV6) GetEnumConstraints() []helpers.FieldEnumConstraint {
	return nil
}

// End of section. //template:end getEnumConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getStringLengthConstraints

// GetStringLengthConstraints returns the version-specific string length constraints
func (data SegmentRoutingV6) GetStringLengthConstraints() []helpers.FieldStringLengthConstraint {
	return nil
}

// End of section. //template:end getStringLengthConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getPatternConstraints

// GetPatternConstraints returns the version-specific string pattern constraints
func (data SegmentRoutingV6) GetPatternConstraints() []helpers.FieldPatternConstraint {
	return nil
}

// End of section. //template:end getPatternConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getDefaultConstraints
// End of section. //template:end getDefaultConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody
func (data *SegmentRoutingV6) updateFromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.GetBytes(res, "enable"); !data.Enable.IsNull() {
		if value.Exists() {
			data.Enable = types.BoolValue(true)
		} else {
			// If config has false and device doesn't have the field, keep false (don't set to null)
			data.Enable = types.BoolValue(false)
		}
	} else if data.Enable.IsNull() {
		data.Enable = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "sid-holdtime"); value.Exists() && !data.SidHoldtime.IsNull() {
		data.SidHoldtime = types.Int64Value(value.Int())
	} else if data.SidHoldtime.IsNull() {
		data.SidHoldtime = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "logging.locator-status"); !data.LoggingLocatorStatus.IsNull() {
		if value.Exists() {
			data.LoggingLocatorStatus = types.BoolValue(true)
		} else {
			// If config has false and device doesn't have the field, keep false (don't set to null)
			data.LoggingLocatorStatus = types.BoolValue(false)
		}
	} else if data.LoggingLocatorStatus.IsNull() {
		data.LoggingLocatorStatus = types.BoolNull()
	}
	for i := range data.Formats {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Formats[i].Name.ValueString()}

		var r gjson.Result
		gjson.GetBytes(res, "formats.formats.format").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("name"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.Formats[i].Name.IsNull() {
			data.Formats[i].Name = types.StringValue(value.String())
		} else {
			data.Formats[i].Name = types.StringNull()
		}
		if value := r.Get("format-enable"); value.Exists() {
			// Only set to true if it was already in the plan (not null)
			if !data.Formats[i].FormatEnable.IsNull() {
				data.Formats[i].FormatEnable = types.BoolValue(true)
			}
		} else {
			// If config has false and device doesn't have the field, keep false (don't set to null)
			// Only set to null if it was already null
			if data.Formats[i].FormatEnable.IsNull() {
				data.Formats[i].FormatEnable = types.BoolNull()
			}
		}
		if value := r.Get("usid.local-id-block-ranges.lib-start"); value.Exists() && !data.Formats[i].UsidLocalIdBlockRangesLibStart.IsNull() {
			data.Formats[i].UsidLocalIdBlockRangesLibStart = types.Int64Value(value.Int())
		} else {
			data.Formats[i].UsidLocalIdBlockRangesLibStart = types.Int64Null()
		}
		if value := r.Get("usid.local-id-block-ranges.explict-lib-start"); value.Exists() && !data.Formats[i].UsidLocalIdBlockRangesExplictLibStart.IsNull() {
			data.Formats[i].UsidLocalIdBlockRangesExplictLibStart = types.Int64Value(value.Int())
		} else {
			data.Formats[i].UsidLocalIdBlockRangesExplictLibStart = types.Int64Null()
		}
		if value := r.Get("usid.wide-local-id-block-explicit-range"); value.Exists() && !data.Formats[i].UsidWideLocalIdBlockExplicitRange.IsNull() {
			data.Formats[i].UsidWideLocalIdBlockExplicitRange = types.Int64Value(value.Int())
		} else {
			data.Formats[i].UsidWideLocalIdBlockExplicitRange = types.Int64Null()
		}
	}
	for i := range data.Locators {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Locators[i].Name.ValueString()}

		var r gjson.Result
		gjson.GetBytes(res, "locators.locators.locator").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("locator-enable"); value.Exists() {
			// Only set to true if it was already in the plan (not null)
			if !data.Locators[i].LocatorEnable.IsNull() {
				data.Locators[i].LocatorEnable = types.BoolValue(true)
			}
		} else {
			// If config has false and device doesn't have the field, keep false (don't set to null)
			// Only set to null if it was already null
			if data.Locators[i].LocatorEnable.IsNull() {
				data.Locators[i].LocatorEnable = types.BoolNull()
			}
		}
		if value := r.Get("name"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.Locators[i].Name.IsNull() {
			data.Locators[i].Name = types.StringValue(value.String())
		} else {
			data.Locators[i].Name = types.StringNull()
		}
		if value := r.Get("micro-segment.behavior"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.Locators[i].MicroSegmentBehavior.IsNull() {
			data.Locators[i].MicroSegmentBehavior = types.StringValue(value.String())
		} else {
			data.Locators[i].MicroSegmentBehavior = types.StringNull()
		}
		if value := r.Get("prefix.prefix"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.Locators[i].Prefix.IsNull() {
			data.Locators[i].Prefix = types.StringValue(value.String())
		} else {
			data.Locators[i].Prefix = types.StringNull()
		}
		if value := r.Get("prefix.prefix-length"); value.Exists() && !data.Locators[i].PrefixLength.IsNull() {
			data.Locators[i].PrefixLength = types.Int64Value(value.Int())
		} else {
			data.Locators[i].PrefixLength = types.Int64Null()
		}
		if value := r.Get("anycast"); value.Exists() {
			// Only set to true if it was already in the plan (not null)
			if !data.Locators[i].Anycast.IsNull() {
				data.Locators[i].Anycast = types.BoolValue(true)
			}
		} else {
			// If config has false and device doesn't have the field, keep false (don't set to null)
			// Only set to null if it was already null
			if data.Locators[i].Anycast.IsNull() {
				data.Locators[i].Anycast = types.BoolNull()
			}
		}
		if value := r.Get("algorithm"); value.Exists() && !data.Locators[i].Algorithm.IsNull() {
			data.Locators[i].Algorithm = types.Int64Value(value.Int())
		} else {
			data.Locators[i].Algorithm = types.Int64Null()
		}
	}
	if value := gjson.GetBytes(res, "encapsulation.traffic-class.option"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.EncapsulationTrafficClassOption.IsNull() {
		data.EncapsulationTrafficClassOption = types.StringValue(value.String())
	} else if data.EncapsulationTrafficClassOption.IsNull() {
		data.EncapsulationTrafficClassOption = types.StringNull()
	}
	if value := gjson.GetBytes(res, "encapsulation.traffic-class.value"); value.Exists() && !data.EncapsulationTrafficClassValue.IsNull() {
		data.EncapsulationTrafficClassValue = types.Int64Value(value.Int())
	} else if data.EncapsulationTrafficClassValue.IsNull() {
		data.EncapsulationTrafficClassValue = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "encapsulation.hop-limit.option"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.EncapsulationHopLimitOption.IsNull() {
		data.EncapsulationHopLimitOption = types.StringValue(value.String())
	} else if data.EncapsulationHopLimitOption.IsNull() {
		data.EncapsulationHopLimitOption = types.StringNull()
	}
	if value := gjson.GetBytes(res, "encapsulation.hop-limit.value"); value.Exists() && !data.EncapsulationHopLimitValue.IsNull() {
		data.EncapsulationHopLimitValue = types.Int64Value(value.Int())
	} else if data.EncapsulationHopLimitValue.IsNull() {
		data.EncapsulationHopLimitValue = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "encapsulation.source-address"); (version == "" || !helpers.VersionAtLeast(version, "26.2")) && value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.EncapsulationSourceAddress.IsNull() {
		data.EncapsulationSourceAddress = types.StringValue(value.String())
	} else if data.EncapsulationSourceAddress.IsNull() {
		data.EncapsulationSourceAddress = types.StringNull()
	}
	if value := gjson.GetBytes(res, "encapsulation.source-address.option"); helpers.VersionAtLeast(version, "26.2") && value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.EncapsulationSourceAddressOption.IsNull() {
		data.EncapsulationSourceAddressOption = types.StringValue(value.String())
	} else if data.EncapsulationSourceAddressOption.IsNull() {
		data.EncapsulationSourceAddressOption = types.StringNull()
	}
	if value := gjson.GetBytes(res, "encapsulation.source-address.address"); helpers.VersionAtLeast(version, "26.2") && value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) && !data.EncapsulationSourceAddressAddress.IsNull() {
		data.EncapsulationSourceAddressAddress = types.StringValue(value.String())
	} else if data.EncapsulationSourceAddressAddress.IsNull() {
		data.EncapsulationSourceAddressAddress = types.StringNull()
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *SegmentRoutingV6) fromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.GetBytes(res, "enable"); value.Exists() {
		data.Enable = types.BoolValue(true)
	} else if !data.Enable.IsNull() {
		// Only set to false if it was previously set in state
		data.Enable = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "sid-holdtime"); value.Exists() {
		data.SidHoldtime = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "logging.locator-status"); value.Exists() {
		data.LoggingLocatorStatus = types.BoolValue(true)
	} else if !data.LoggingLocatorStatus.IsNull() {
		// Only set to false if it was previously set in state
		data.LoggingLocatorStatus = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "formats.formats.format"); value.Exists() {
		data.Formats = make([]SegmentRoutingV6Formats, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := SegmentRoutingV6Formats{}
			if cValue := v.Get("name"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Name = types.StringValue(cValue.String())
			}
			if cValue := v.Get("format-enable"); cValue.Exists() {
				item.FormatEnable = types.BoolValue(true)
			} else if !item.FormatEnable.IsNull() {
				// Only set to false if it was previously set
				item.FormatEnable = types.BoolValue(false)
			}
			if cValue := v.Get("usid.local-id-block-ranges.lib-start"); cValue.Exists() {
				item.UsidLocalIdBlockRangesLibStart = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("usid.local-id-block-ranges.explict-lib-start"); cValue.Exists() {
				item.UsidLocalIdBlockRangesExplictLibStart = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("usid.wide-local-id-block-explicit-range"); cValue.Exists() {
				item.UsidWideLocalIdBlockExplicitRange = types.Int64Value(cValue.Int())
			}
			data.Formats = append(data.Formats, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "locators.locators.locator"); value.Exists() {
		data.Locators = make([]SegmentRoutingV6Locators, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := SegmentRoutingV6Locators{}
			if cValue := v.Get("locator-enable"); cValue.Exists() {
				item.LocatorEnable = types.BoolValue(true)
			} else if !item.LocatorEnable.IsNull() {
				// Only set to false if it was previously set
				item.LocatorEnable = types.BoolValue(false)
			}
			if cValue := v.Get("name"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Name = types.StringValue(cValue.String())
			}
			if cValue := v.Get("micro-segment.behavior"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.MicroSegmentBehavior = types.StringValue(cValue.String())
			}
			if cValue := v.Get("prefix.prefix"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Prefix = types.StringValue(cValue.String())
			}
			if cValue := v.Get("prefix.prefix-length"); cValue.Exists() {
				item.PrefixLength = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("anycast"); cValue.Exists() {
				item.Anycast = types.BoolValue(true)
			} else if !item.Anycast.IsNull() {
				// Only set to false if it was previously set
				item.Anycast = types.BoolValue(false)
			}
			if cValue := v.Get("algorithm"); cValue.Exists() {
				item.Algorithm = types.Int64Value(cValue.Int())
			}
			data.Locators = append(data.Locators, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "encapsulation.traffic-class.option"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.EncapsulationTrafficClassOption = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "encapsulation.traffic-class.value"); value.Exists() {
		data.EncapsulationTrafficClassValue = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "encapsulation.hop-limit.option"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.EncapsulationHopLimitOption = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "encapsulation.hop-limit.value"); value.Exists() {
		data.EncapsulationHopLimitValue = types.Int64Value(value.Int())
	}
	if version == "" || !helpers.VersionAtLeast(version, "26.2") {
		if value := gjson.GetBytes(res, "encapsulation.source-address"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
			data.EncapsulationSourceAddress = types.StringValue(value.String())
		}
	} else {
		data.EncapsulationSourceAddress = types.StringNull()
	}
	if helpers.VersionAtLeast(version, "26.2") {
		if value := gjson.GetBytes(res, "encapsulation.source-address.option"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
			data.EncapsulationSourceAddressOption = types.StringValue(value.String())
		}
	} else {
		data.EncapsulationSourceAddressOption = types.StringNull()
	}
	if helpers.VersionAtLeast(version, "26.2") {
		if value := gjson.GetBytes(res, "encapsulation.source-address.address"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
			data.EncapsulationSourceAddressAddress = types.StringValue(value.String())
		}
	} else {
		data.EncapsulationSourceAddressAddress = types.StringNull()
	}
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyData

func (data *SegmentRoutingV6Data) fromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.GetBytes(res, "enable"); value.Exists() {
		data.Enable = types.BoolValue(true)
	} else {
		data.Enable = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "sid-holdtime"); value.Exists() {
		data.SidHoldtime = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "logging.locator-status"); value.Exists() {
		data.LoggingLocatorStatus = types.BoolValue(true)
	} else {
		data.LoggingLocatorStatus = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "formats.formats.format"); value.Exists() {
		data.Formats = make([]SegmentRoutingV6Formats, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := SegmentRoutingV6Formats{}
			if cValue := v.Get("name"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Name = types.StringValue(cValue.String())
			}
			if cValue := v.Get("format-enable"); cValue.Exists() {
				item.FormatEnable = types.BoolValue(true)
			} else {
				item.FormatEnable = types.BoolValue(false)
			}
			if cValue := v.Get("usid.local-id-block-ranges.lib-start"); cValue.Exists() {
				item.UsidLocalIdBlockRangesLibStart = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("usid.local-id-block-ranges.explict-lib-start"); cValue.Exists() {
				item.UsidLocalIdBlockRangesExplictLibStart = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("usid.wide-local-id-block-explicit-range"); cValue.Exists() {
				item.UsidWideLocalIdBlockExplicitRange = types.Int64Value(cValue.Int())
			}
			data.Formats = append(data.Formats, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "locators.locators.locator"); value.Exists() {
		data.Locators = make([]SegmentRoutingV6Locators, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := SegmentRoutingV6Locators{}
			if cValue := v.Get("locator-enable"); cValue.Exists() {
				item.LocatorEnable = types.BoolValue(true)
			} else {
				item.LocatorEnable = types.BoolValue(false)
			}
			if cValue := v.Get("name"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Name = types.StringValue(cValue.String())
			}
			if cValue := v.Get("micro-segment.behavior"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.MicroSegmentBehavior = types.StringValue(cValue.String())
			}
			if cValue := v.Get("prefix.prefix"); cValue.Exists() && (cValue.Type == gjson.String || cValue.Type == gjson.Number) {
				item.Prefix = types.StringValue(cValue.String())
			}
			if cValue := v.Get("prefix.prefix-length"); cValue.Exists() {
				item.PrefixLength = types.Int64Value(cValue.Int())
			}
			if cValue := v.Get("anycast"); cValue.Exists() {
				item.Anycast = types.BoolValue(true)
			} else {
				item.Anycast = types.BoolValue(false)
			}
			if cValue := v.Get("algorithm"); cValue.Exists() {
				item.Algorithm = types.Int64Value(cValue.Int())
			}
			data.Locators = append(data.Locators, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "encapsulation.traffic-class.option"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.EncapsulationTrafficClassOption = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "encapsulation.traffic-class.value"); value.Exists() {
		data.EncapsulationTrafficClassValue = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "encapsulation.hop-limit.option"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.EncapsulationHopLimitOption = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "encapsulation.hop-limit.value"); value.Exists() {
		data.EncapsulationHopLimitValue = types.Int64Value(value.Int())
	}
	if version == "" || !helpers.VersionAtLeast(version, "26.2") {
		if value := gjson.GetBytes(res, "encapsulation.source-address"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
			data.EncapsulationSourceAddress = types.StringValue(value.String())
		}
	} else {
		data.EncapsulationSourceAddress = types.StringNull()
	}
	if helpers.VersionAtLeast(version, "26.2") {
		if value := gjson.GetBytes(res, "encapsulation.source-address.option"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
			data.EncapsulationSourceAddressOption = types.StringValue(value.String())
		}
	} else {
		data.EncapsulationSourceAddressOption = types.StringNull()
	}
	if helpers.VersionAtLeast(version, "26.2") {
		if value := gjson.GetBytes(res, "encapsulation.source-address.address"); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
			data.EncapsulationSourceAddressAddress = types.StringValue(value.String())
		}
	} else {
		data.EncapsulationSourceAddressAddress = types.StringNull()
	}
}

// End of section. //template:end fromBodyData

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletedItems

func (data *SegmentRoutingV6) getDeletedItems(ctx context.Context, state SegmentRoutingV6, version string) []string {
	deletedItems := make([]string, 0)
	if helpers.VersionAtLeast(version, "26.2") && !state.EncapsulationSourceAddressAddress.IsNull() && data.EncapsulationSourceAddressAddress.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "encapsulation/source-address/address"))
	}
	if helpers.VersionAtLeast(version, "26.2") && !state.EncapsulationSourceAddressOption.IsNull() && data.EncapsulationSourceAddressOption.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "encapsulation/source-address/option"))
	}
	if (version == "" || !helpers.VersionAtLeast(version, "26.2")) && !state.EncapsulationSourceAddress.IsNull() && data.EncapsulationSourceAddress.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "encapsulation/source-address"))
	}
	if !state.EncapsulationHopLimitValue.IsNull() && data.EncapsulationHopLimitValue.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "encapsulation/hop-limit/value"))
	}
	if !state.EncapsulationHopLimitOption.IsNull() && data.EncapsulationHopLimitOption.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "encapsulation/hop-limit/option"))
	}
	if !state.EncapsulationTrafficClassValue.IsNull() && data.EncapsulationTrafficClassValue.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "encapsulation/traffic-class/value"))
	}
	if !state.EncapsulationTrafficClassOption.IsNull() && data.EncapsulationTrafficClassOption.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "encapsulation/traffic-class/option"))
	}
	for i := range state.Locators {
		keys := [...]string{"name"}
		stateKeyValues := [...]string{state.Locators[i].Name.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + stateKeyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Locators[i].Name.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Locators {
			found = true
			if state.Locators[i].Name.ValueString() != data.Locators[j].Name.ValueString() {
				found = false
			}
			if found {
				if !state.Locators[i].Algorithm.IsNull() && data.Locators[j].Algorithm.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "locators/locators/locator", keyString), "algorithm"))
				}
				if !state.Locators[i].Anycast.IsNull() && data.Locators[j].Anycast.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "locators/locators/locator", keyString), "anycast"))
				}
				if !state.Locators[i].PrefixLength.IsNull() && data.Locators[j].PrefixLength.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "locators/locators/locator", keyString), "prefix/prefix-length"))
				}
				if !state.Locators[i].Prefix.IsNull() && data.Locators[j].Prefix.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "locators/locators/locator", keyString), "prefix/prefix"))
				}
				if !state.Locators[i].MicroSegmentBehavior.IsNull() && data.Locators[j].MicroSegmentBehavior.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "locators/locators/locator", keyString), "micro-segment/behavior"))
				}
				if !state.Locators[i].LocatorEnable.IsNull() && data.Locators[j].LocatorEnable.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "locators/locators/locator", keyString), "locator-enable"))
				}
				break
			}
		}
		if !found {
			deletedItems = append(deletedItems, fmt.Sprintf("%v/%v%v", state.getPath(), "locators/locators/locator", keyString))
		}
	}
	for i := range state.Formats {
		keys := [...]string{"name"}
		stateKeyValues := [...]string{state.Formats[i].Name.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + stateKeyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Formats[i].Name.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Formats {
			found = true
			if state.Formats[i].Name.ValueString() != data.Formats[j].Name.ValueString() {
				found = false
			}
			if found {
				if !state.Formats[i].UsidWideLocalIdBlockExplicitRange.IsNull() && data.Formats[j].UsidWideLocalIdBlockExplicitRange.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "formats/formats/format", keyString), "usid/wide-local-id-block-explicit-range"))
				}
				if !state.Formats[i].UsidLocalIdBlockRangesExplictLibStart.IsNull() && data.Formats[j].UsidLocalIdBlockRangesExplictLibStart.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "formats/formats/format", keyString), "usid/local-id-block-ranges/explict-lib-start"))
				}
				if !state.Formats[i].UsidLocalIdBlockRangesLibStart.IsNull() && data.Formats[j].UsidLocalIdBlockRangesLibStart.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "formats/formats/format", keyString), "usid/local-id-block-ranges/lib-start"))
				}
				if !state.Formats[i].FormatEnable.IsNull() && data.Formats[j].FormatEnable.IsNull() {
					deletedItems = append(deletedItems, path.Join(fmt.Sprintf("%v/%v%v", state.getPath(), "formats/formats/format", keyString), "format-enable"))
				}
				break
			}
		}
		if !found {
			deletedItems = append(deletedItems, fmt.Sprintf("%v/%v%v", state.getPath(), "formats/formats/format", keyString))
		}
	}
	if !state.LoggingLocatorStatus.IsNull() && data.LoggingLocatorStatus.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "logging/locator-status"))
	}
	if !state.SidHoldtime.IsNull() && data.SidHoldtime.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "sid-holdtime"))
	}
	if !state.Enable.IsNull() && data.Enable.IsNull() {
		deletedItems = append(deletedItems, path.Join(state.getPath(), "enable"))
	}
	return deletedItems
}

// End of section. //template:end getDeletedItems

// Section below is generated&owned by "gen/generator.go". //template:begin getEmptyLeafsDelete

func (data *SegmentRoutingV6) getEmptyLeafsDelete(ctx context.Context, state *SegmentRoutingV6, version string) []string {
	emptyLeafsDelete := make([]string, 0)
	for i := range data.Locators {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Locators[i].Name.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
		if !data.Locators[i].Anycast.IsNull() && !data.Locators[i].Anycast.ValueBool() {
			if state == nil || i >= len(state.Locators) || state.Locators[i].Anycast.IsNull() || state.Locators[i].Anycast.ValueBool() {
				emptyLeafsDelete = append(emptyLeafsDelete, path.Join(fmt.Sprintf("%v/%v%v", data.getPath(), "locators/locators/locator", keyString), "anycast"))
			}
		}
		if !data.Locators[i].LocatorEnable.IsNull() && !data.Locators[i].LocatorEnable.ValueBool() {
			if state == nil || i >= len(state.Locators) || state.Locators[i].LocatorEnable.IsNull() || state.Locators[i].LocatorEnable.ValueBool() {
				emptyLeafsDelete = append(emptyLeafsDelete, path.Join(fmt.Sprintf("%v/%v%v", data.getPath(), "locators/locators/locator", keyString), "locator-enable"))
			}
		}
	}
	for i := range data.Formats {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Formats[i].Name.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
		if !data.Formats[i].FormatEnable.IsNull() && !data.Formats[i].FormatEnable.ValueBool() {
			if state == nil || i >= len(state.Formats) || state.Formats[i].FormatEnable.IsNull() || state.Formats[i].FormatEnable.ValueBool() {
				emptyLeafsDelete = append(emptyLeafsDelete, path.Join(fmt.Sprintf("%v/%v%v", data.getPath(), "formats/formats/format", keyString), "format-enable"))
			}
		}
	}
	if !data.LoggingLocatorStatus.IsNull() && !data.LoggingLocatorStatus.ValueBool() {
		if state == nil || state.LoggingLocatorStatus.IsNull() || state.LoggingLocatorStatus.ValueBool() {
			emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "logging/locator-status"))
		}
	}
	if !data.Enable.IsNull() && !data.Enable.ValueBool() {
		if state == nil || state.Enable.IsNull() || state.Enable.ValueBool() {
			emptyLeafsDelete = append(emptyLeafsDelete, path.Join(data.getPath(), "enable"))
		}
	}
	return emptyLeafsDelete
}

// End of section. //template:end getEmptyLeafsDelete

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletePaths
func (data *SegmentRoutingV6) getDeletePaths(ctx context.Context, version string) []string {
	var deletePaths []string
	if helpers.VersionAtLeast(version, "26.2") && !data.EncapsulationSourceAddressAddress.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "encapsulation/source-address/address"))
	}
	if helpers.VersionAtLeast(version, "26.2") && !data.EncapsulationSourceAddressOption.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "encapsulation/source-address/option"))
	}
	if (version == "" || !helpers.VersionAtLeast(version, "26.2")) && !data.EncapsulationSourceAddress.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "encapsulation/source-address"))
	}
	if !data.EncapsulationHopLimitValue.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "encapsulation/hop-limit/value"))
	}
	if !data.EncapsulationHopLimitOption.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "encapsulation/hop-limit/option"))
	}
	if !data.EncapsulationTrafficClassValue.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "encapsulation/traffic-class/value"))
	}
	if !data.EncapsulationTrafficClassOption.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "encapsulation/traffic-class/option"))
	}
	for i := range data.Locators {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Locators[i].Name.ValueString()}

		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(data.Locators[i].Name.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}
		deletePaths = append(deletePaths, fmt.Sprintf("%v/%v%v", data.getPath(), "locators/locators/locator", keyString))
	}
	for i := range data.Formats {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Formats[i].Name.ValueString()}

		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(data.Formats[i].Name.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}
		deletePaths = append(deletePaths, fmt.Sprintf("%v/%v%v", data.getPath(), "formats/formats/format", keyString))
	}
	if !data.LoggingLocatorStatus.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "logging/locator-status"))
	}
	if !data.SidHoldtime.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "sid-holdtime"))
	}
	if !data.Enable.IsNull() {
		deletePaths = append(deletePaths, path.Join(data.getPath(), "enable"))
	}

	return deletePaths
}

// End of section. //template:end getDeletePaths

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data SegmentRoutingV6) toBodyXML(ctx context.Context, stateArg ...*SegmentRoutingV6) string {
	var state *SegmentRoutingV6
	if len(stateArg) > 0 {
		state = stateArg[0]
	}
	body := netconf.Body{}
	if !data.Enable.IsNull() && !data.Enable.IsUnknown() {
		if data.Enable.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/enable", "")
		}
	}
	if !data.SidHoldtime.IsNull() && !data.SidHoldtime.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/sid-holdtime", strconv.FormatInt(data.SidHoldtime.ValueInt64(), 10))
	}
	if !data.LoggingLocatorStatus.IsNull() && !data.LoggingLocatorStatus.IsUnknown() {
		if data.LoggingLocatorStatus.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/logging/locator-status", "")
		}
	}
	if len(data.Formats) > 0 {
		for _, item := range data.Formats {
			basePath := data.getXPath() + "/formats/formats/format[name='" + item.Name.ValueString() + "']"
			if !item.Name.IsNull() && !item.Name.IsUnknown() {
				body = helpers.SetFromXPath(body, basePath+"/name", item.Name.ValueString())
			}
			if !item.FormatEnable.IsNull() && !item.FormatEnable.IsUnknown() {
				if item.FormatEnable.ValueBool() {
					body = helpers.SetFromXPath(body, basePath+"/format-enable", "")
				}
			}
			if !item.UsidLocalIdBlockRangesLibStart.IsNull() && !item.UsidLocalIdBlockRangesLibStart.IsUnknown() {
				body = helpers.SetFromXPath(body, basePath+"/usid/local-id-block-ranges/lib-start", strconv.FormatInt(item.UsidLocalIdBlockRangesLibStart.ValueInt64(), 10))
			}
			if !item.UsidLocalIdBlockRangesExplictLibStart.IsNull() && !item.UsidLocalIdBlockRangesExplictLibStart.IsUnknown() {
				body = helpers.SetFromXPath(body, basePath+"/usid/local-id-block-ranges/explict-lib-start", strconv.FormatInt(item.UsidLocalIdBlockRangesExplictLibStart.ValueInt64(), 10))
			}
			if !item.UsidWideLocalIdBlockExplicitRange.IsNull() && !item.UsidWideLocalIdBlockExplicitRange.IsUnknown() {
				body = helpers.SetFromXPath(body, basePath+"/usid/wide-local-id-block-explicit-range", strconv.FormatInt(item.UsidWideLocalIdBlockExplicitRange.ValueInt64(), 10))
			}
		}
	}
	if len(data.Locators) > 0 {
		for _, item := range data.Locators {
			basePath := data.getXPath() + "/locators/locators/locator[name='" + item.Name.ValueString() + "']"
			if !item.LocatorEnable.IsNull() && !item.LocatorEnable.IsUnknown() {
				if item.LocatorEnable.ValueBool() {
					body = helpers.SetFromXPath(body, basePath+"/locator-enable", "")
				}
			}
			if !item.Name.IsNull() && !item.Name.IsUnknown() {
				body = helpers.SetFromXPath(body, basePath+"/name", item.Name.ValueString())
			}
			if !item.MicroSegmentBehavior.IsNull() && !item.MicroSegmentBehavior.IsUnknown() {
				body = helpers.SetFromXPath(body, basePath+"/micro-segment/behavior", item.MicroSegmentBehavior.ValueString())
			}
			if !item.Prefix.IsNull() && !item.Prefix.IsUnknown() {
				body = helpers.SetFromXPath(body, basePath+"/prefix/prefix", item.Prefix.ValueString())
			}
			if !item.PrefixLength.IsNull() && !item.PrefixLength.IsUnknown() {
				body = helpers.SetFromXPath(body, basePath+"/prefix/prefix-length", strconv.FormatInt(item.PrefixLength.ValueInt64(), 10))
			}
			if !item.Anycast.IsNull() && !item.Anycast.IsUnknown() {
				if item.Anycast.ValueBool() {
					body = helpers.SetFromXPath(body, basePath+"/anycast", "")
				}
			}
			if !item.Algorithm.IsNull() && !item.Algorithm.IsUnknown() {
				body = helpers.SetFromXPath(body, basePath+"/algorithm", strconv.FormatInt(item.Algorithm.ValueInt64(), 10))
			}
		}
	}
	if !data.EncapsulationTrafficClassOption.IsNull() && !data.EncapsulationTrafficClassOption.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/encapsulation/traffic-class/option", data.EncapsulationTrafficClassOption.ValueString())
	}
	if !data.EncapsulationTrafficClassValue.IsNull() && !data.EncapsulationTrafficClassValue.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/encapsulation/traffic-class/value", strconv.FormatInt(data.EncapsulationTrafficClassValue.ValueInt64(), 10))
	}
	if !data.EncapsulationHopLimitOption.IsNull() && !data.EncapsulationHopLimitOption.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/encapsulation/hop-limit/option", data.EncapsulationHopLimitOption.ValueString())
	}
	if !data.EncapsulationHopLimitValue.IsNull() && !data.EncapsulationHopLimitValue.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/encapsulation/hop-limit/value", strconv.FormatInt(data.EncapsulationHopLimitValue.ValueInt64(), 10))
	}
	if !data.EncapsulationSourceAddress.IsNull() && !data.EncapsulationSourceAddress.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/encapsulation/source-address", data.EncapsulationSourceAddress.ValueString())
	}
	if !data.EncapsulationSourceAddressOption.IsNull() && !data.EncapsulationSourceAddressOption.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/encapsulation/source-address/option", data.EncapsulationSourceAddressOption.ValueString())
	}
	if !data.EncapsulationSourceAddressAddress.IsNull() && !data.EncapsulationSourceAddressAddress.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/encapsulation/source-address/address", data.EncapsulationSourceAddressAddress.ValueString())
	}
	bodyString, err := helpers.BodyToNestedXML(body)
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to nested XML: %s", err))
		// If there's an error (e.g., invalid path syntax for xmlns attributes), return empty string
		// This allows XML namespace siblings to be handled separately
		return ""
	}
	bodyString = helpers.AddNamespaceToRootElement(bodyString, data.getXPath())
	// On Create, seed the keyed base node when no leaves were emitted so a
	// keys-only entry (e.g. address-family ipv4 unicast) isn't sent as an empty
	// body, which EditConfig skips — creating drift. Uses default merge
	// (RFC 6241 §7.2); getXPath()'s key gives a valid minimal list entry
	// (RFC 7950 §7.8.2). Create-only (state == nil) leaves Update untouched.
	if bodyString == "" && state == nil {
		seededBody, seedErr := helpers.BodyToNestedXML(helpers.SetFromXPath(netconf.Body{}, data.getXPath(), ""))
		if seedErr != nil {
			tflog.Error(ctx, fmt.Sprintf("Error seeding keys-only base node: %s", seedErr))
		} else {
			bodyString = helpers.AddNamespaceToRootElement(seededBody, data.getXPath())
		}
	}
	// Append delete XML for empty bool leafs (false values that need explicit removal)
	for _, deletePath := range data.getEmptyLeafsDelete(ctx, state, "") {
		bodyString += helpers.RemoveFromXPath(netconf.Body{}, deletePath).Res()
	}
	tflog.Debug(ctx, fmt.Sprintf("toBodyXML: generated body length: %d", len(bodyString)))
	return bodyString
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *SegmentRoutingV6) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/enable"); value.Exists() {
		// Only set to true if it was already in the plan (not null)
		if !data.Enable.IsNull() {
			data.Enable = types.BoolValue(true)
		}
	} else {
		// For presence-based booleans, only set to null if it's already null
		if data.Enable.IsNull() {
			data.Enable = types.BoolNull()
		}
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/sid-holdtime"); value.Exists() && !data.SidHoldtime.IsNull() {
		data.SidHoldtime = types.Int64Value(value.Int())
	} else if data.SidHoldtime.IsNull() {
		data.SidHoldtime = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/logging/locator-status"); value.Exists() {
		// Only set to true if it was already in the plan (not null)
		if !data.LoggingLocatorStatus.IsNull() {
			data.LoggingLocatorStatus = types.BoolValue(true)
		}
	} else {
		// For presence-based booleans, only set to null if it's already null
		if data.LoggingLocatorStatus.IsNull() {
			data.LoggingLocatorStatus = types.BoolNull()
		}
	}
	for i := range data.Formats {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Formats[i].Name.ValueString()}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data/"+data.getXPath()+"/formats/formats/format").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "name"); value.Exists() && !data.Formats[i].Name.IsNull() {
			data.Formats[i].Name = types.StringValue(value.String())
		} else if data.Formats[i].Name.IsNull() {
			data.Formats[i].Name = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "format-enable"); value.Exists() {
			// Only set to true if it was already in the plan (not null)
			if !data.Formats[i].FormatEnable.IsNull() {
				data.Formats[i].FormatEnable = types.BoolValue(true)
			}
		} else {
			// If config has false and device doesn't have the field, keep false (don't set to null)
			// Only set to null if it was already null
			if data.Formats[i].FormatEnable.IsNull() {
				data.Formats[i].FormatEnable = types.BoolNull()
			}
		}
		if value := helpers.GetFromXPath(r, "usid/local-id-block-ranges/lib-start"); value.Exists() && !data.Formats[i].UsidLocalIdBlockRangesLibStart.IsNull() {
			data.Formats[i].UsidLocalIdBlockRangesLibStart = types.Int64Value(value.Int())
		} else if data.Formats[i].UsidLocalIdBlockRangesLibStart.IsNull() {
			data.Formats[i].UsidLocalIdBlockRangesLibStart = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "usid/local-id-block-ranges/explict-lib-start"); value.Exists() && !data.Formats[i].UsidLocalIdBlockRangesExplictLibStart.IsNull() {
			data.Formats[i].UsidLocalIdBlockRangesExplictLibStart = types.Int64Value(value.Int())
		} else if data.Formats[i].UsidLocalIdBlockRangesExplictLibStart.IsNull() {
			data.Formats[i].UsidLocalIdBlockRangesExplictLibStart = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "usid/wide-local-id-block-explicit-range"); value.Exists() && !data.Formats[i].UsidWideLocalIdBlockExplicitRange.IsNull() {
			data.Formats[i].UsidWideLocalIdBlockExplicitRange = types.Int64Value(value.Int())
		} else if data.Formats[i].UsidWideLocalIdBlockExplicitRange.IsNull() {
			data.Formats[i].UsidWideLocalIdBlockExplicitRange = types.Int64Null()
		}
	}
	for i := range data.Locators {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Locators[i].Name.ValueString()}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data/"+data.getXPath()+"/locators/locators/locator").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "locator-enable"); value.Exists() {
			// Only set to true if it was already in the plan (not null)
			if !data.Locators[i].LocatorEnable.IsNull() {
				data.Locators[i].LocatorEnable = types.BoolValue(true)
			}
		} else {
			// If config has false and device doesn't have the field, keep false (don't set to null)
			// Only set to null if it was already null
			if data.Locators[i].LocatorEnable.IsNull() {
				data.Locators[i].LocatorEnable = types.BoolNull()
			}
		}
		if value := helpers.GetFromXPath(r, "name"); value.Exists() && !data.Locators[i].Name.IsNull() {
			data.Locators[i].Name = types.StringValue(value.String())
		} else if data.Locators[i].Name.IsNull() {
			data.Locators[i].Name = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "micro-segment/behavior"); value.Exists() && !data.Locators[i].MicroSegmentBehavior.IsNull() {
			data.Locators[i].MicroSegmentBehavior = types.StringValue(value.String())
		} else if data.Locators[i].MicroSegmentBehavior.IsNull() {
			data.Locators[i].MicroSegmentBehavior = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "prefix/prefix"); value.Exists() && !data.Locators[i].Prefix.IsNull() {
			data.Locators[i].Prefix = types.StringValue(value.String())
		} else if data.Locators[i].Prefix.IsNull() {
			data.Locators[i].Prefix = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "prefix/prefix-length"); value.Exists() && !data.Locators[i].PrefixLength.IsNull() {
			data.Locators[i].PrefixLength = types.Int64Value(value.Int())
		} else if data.Locators[i].PrefixLength.IsNull() {
			data.Locators[i].PrefixLength = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "anycast"); value.Exists() {
			// Only set to true if it was already in the plan (not null)
			if !data.Locators[i].Anycast.IsNull() {
				data.Locators[i].Anycast = types.BoolValue(true)
			}
		} else {
			// If config has false and device doesn't have the field, keep false (don't set to null)
			// Only set to null if it was already null
			if data.Locators[i].Anycast.IsNull() {
				data.Locators[i].Anycast = types.BoolNull()
			}
		}
		if value := helpers.GetFromXPath(r, "algorithm"); value.Exists() && !data.Locators[i].Algorithm.IsNull() {
			data.Locators[i].Algorithm = types.Int64Value(value.Int())
		} else if data.Locators[i].Algorithm.IsNull() {
			data.Locators[i].Algorithm = types.Int64Null()
		}
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/traffic-class/option"); value.Exists() && !data.EncapsulationTrafficClassOption.IsNull() {
		data.EncapsulationTrafficClassOption = types.StringValue(value.String())
	} else if data.EncapsulationTrafficClassOption.IsNull() {
		data.EncapsulationTrafficClassOption = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/traffic-class/value"); value.Exists() && !data.EncapsulationTrafficClassValue.IsNull() {
		data.EncapsulationTrafficClassValue = types.Int64Value(value.Int())
	} else if data.EncapsulationTrafficClassValue.IsNull() {
		data.EncapsulationTrafficClassValue = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/hop-limit/option"); value.Exists() && !data.EncapsulationHopLimitOption.IsNull() {
		data.EncapsulationHopLimitOption = types.StringValue(value.String())
	} else if data.EncapsulationHopLimitOption.IsNull() {
		data.EncapsulationHopLimitOption = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/hop-limit/value"); value.Exists() && !data.EncapsulationHopLimitValue.IsNull() {
		data.EncapsulationHopLimitValue = types.Int64Value(value.Int())
	} else if data.EncapsulationHopLimitValue.IsNull() {
		data.EncapsulationHopLimitValue = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/source-address"); value.Exists() && !data.EncapsulationSourceAddress.IsNull() {
		data.EncapsulationSourceAddress = types.StringValue(value.String())
	} else if data.EncapsulationSourceAddress.IsNull() {
		data.EncapsulationSourceAddress = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/source-address/option"); value.Exists() && !data.EncapsulationSourceAddressOption.IsNull() {
		data.EncapsulationSourceAddressOption = types.StringValue(value.String())
	} else if data.EncapsulationSourceAddressOption.IsNull() {
		data.EncapsulationSourceAddressOption = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/source-address/address"); value.Exists() && !data.EncapsulationSourceAddressAddress.IsNull() {
		data.EncapsulationSourceAddressAddress = types.StringValue(value.String())
	} else if data.EncapsulationSourceAddressAddress.IsNull() {
		data.EncapsulationSourceAddressAddress = types.StringNull()
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *SegmentRoutingV6) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/enable"); value.Exists() {
		data.Enable = types.BoolValue(true)
	} else {
		data.Enable = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/sid-holdtime"); value.Exists() {
		data.SidHoldtime = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/logging/locator-status"); value.Exists() {
		data.LoggingLocatorStatus = types.BoolValue(true)
	} else {
		data.LoggingLocatorStatus = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/formats/formats/format"); value.Exists() {
		data.Formats = make([]SegmentRoutingV6Formats, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SegmentRoutingV6Formats{}
			if cValue := helpers.GetFromXPath(v, "name"); cValue.Exists() {
				item.Name = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "format-enable"); cValue.Exists() {
				item.FormatEnable = types.BoolValue(true)
			} else {
				item.FormatEnable = types.BoolValue(false)
			}
			if cValue := helpers.GetFromXPath(v, "usid/local-id-block-ranges/lib-start"); cValue.Exists() {
				item.UsidLocalIdBlockRangesLibStart = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "usid/local-id-block-ranges/explict-lib-start"); cValue.Exists() {
				item.UsidLocalIdBlockRangesExplictLibStart = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "usid/wide-local-id-block-explicit-range"); cValue.Exists() {
				item.UsidWideLocalIdBlockExplicitRange = types.Int64Value(cValue.Int())
			}
			data.Formats = append(data.Formats, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/locators/locators/locator"); value.Exists() {
		data.Locators = make([]SegmentRoutingV6Locators, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SegmentRoutingV6Locators{}
			if cValue := helpers.GetFromXPath(v, "locator-enable"); cValue.Exists() {
				item.LocatorEnable = types.BoolValue(true)
			} else {
				item.LocatorEnable = types.BoolValue(false)
			}
			if cValue := helpers.GetFromXPath(v, "name"); cValue.Exists() {
				item.Name = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "micro-segment/behavior"); cValue.Exists() {
				item.MicroSegmentBehavior = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "prefix/prefix"); cValue.Exists() {
				item.Prefix = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "prefix/prefix-length"); cValue.Exists() {
				item.PrefixLength = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "anycast"); cValue.Exists() {
				item.Anycast = types.BoolValue(true)
			} else {
				item.Anycast = types.BoolValue(false)
			}
			if cValue := helpers.GetFromXPath(v, "algorithm"); cValue.Exists() {
				item.Algorithm = types.Int64Value(cValue.Int())
			}
			data.Locators = append(data.Locators, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/traffic-class/option"); value.Exists() {
		data.EncapsulationTrafficClassOption = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/traffic-class/value"); value.Exists() {
		data.EncapsulationTrafficClassValue = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/hop-limit/option"); value.Exists() {
		data.EncapsulationHopLimitOption = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/hop-limit/value"); value.Exists() {
		data.EncapsulationHopLimitValue = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/source-address"); value.Exists() {
		data.EncapsulationSourceAddress = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/source-address/option"); value.Exists() {
		data.EncapsulationSourceAddressOption = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/source-address/address"); value.Exists() {
		data.EncapsulationSourceAddressAddress = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *SegmentRoutingV6Data) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/enable"); value.Exists() {
		data.Enable = types.BoolValue(true)
	} else {
		data.Enable = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/sid-holdtime"); value.Exists() {
		data.SidHoldtime = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/logging/locator-status"); value.Exists() {
		data.LoggingLocatorStatus = types.BoolValue(true)
	} else {
		data.LoggingLocatorStatus = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/formats/formats/format"); value.Exists() {
		data.Formats = make([]SegmentRoutingV6Formats, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SegmentRoutingV6Formats{}
			if cValue := helpers.GetFromXPath(v, "name"); cValue.Exists() {
				item.Name = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "format-enable"); cValue.Exists() {
				item.FormatEnable = types.BoolValue(true)
			} else {
				item.FormatEnable = types.BoolValue(false)
			}
			if cValue := helpers.GetFromXPath(v, "usid/local-id-block-ranges/lib-start"); cValue.Exists() {
				item.UsidLocalIdBlockRangesLibStart = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "usid/local-id-block-ranges/explict-lib-start"); cValue.Exists() {
				item.UsidLocalIdBlockRangesExplictLibStart = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "usid/wide-local-id-block-explicit-range"); cValue.Exists() {
				item.UsidWideLocalIdBlockExplicitRange = types.Int64Value(cValue.Int())
			}
			data.Formats = append(data.Formats, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/locators/locators/locator"); value.Exists() {
		data.Locators = make([]SegmentRoutingV6Locators, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SegmentRoutingV6Locators{}
			if cValue := helpers.GetFromXPath(v, "locator-enable"); cValue.Exists() {
				item.LocatorEnable = types.BoolValue(true)
			} else {
				item.LocatorEnable = types.BoolValue(false)
			}
			if cValue := helpers.GetFromXPath(v, "name"); cValue.Exists() {
				item.Name = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "micro-segment/behavior"); cValue.Exists() {
				item.MicroSegmentBehavior = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "prefix/prefix"); cValue.Exists() {
				item.Prefix = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "prefix/prefix-length"); cValue.Exists() {
				item.PrefixLength = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "anycast"); cValue.Exists() {
				item.Anycast = types.BoolValue(true)
			} else {
				item.Anycast = types.BoolValue(false)
			}
			if cValue := helpers.GetFromXPath(v, "algorithm"); cValue.Exists() {
				item.Algorithm = types.Int64Value(cValue.Int())
			}
			data.Locators = append(data.Locators, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/traffic-class/option"); value.Exists() {
		data.EncapsulationTrafficClassOption = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/traffic-class/value"); value.Exists() {
		data.EncapsulationTrafficClassValue = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/hop-limit/option"); value.Exists() {
		data.EncapsulationHopLimitOption = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/hop-limit/value"); value.Exists() {
		data.EncapsulationHopLimitValue = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/source-address"); value.Exists() {
		data.EncapsulationSourceAddress = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/source-address/option"); value.Exists() {
		data.EncapsulationSourceAddressOption = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/encapsulation/source-address/address"); value.Exists() {
		data.EncapsulationSourceAddressAddress = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *SegmentRoutingV6) addDeletedItemsXML(ctx context.Context, state SegmentRoutingV6, body string) string {
	// Start with an empty body - we'll build up the delete operations
	b := netconf.Body{}
	deletedPaths := make(map[string]bool)
	_ = deletedPaths // Avoid unused variable error when no delete_parent attributes exist
	if !state.EncapsulationSourceAddressAddress.IsNull() && data.EncapsulationSourceAddressAddress.IsNull() {
		deletePath := state.getXPath() + "/encapsulation/source-address/address"
		// Check if a parent path is already marked for deletion
		parentAlreadyDeleted := false
		for dp := range deletedPaths {
			if strings.HasPrefix(deletePath, dp+"/") {
				parentAlreadyDeleted = true
				break
			}
		}
		if !parentAlreadyDeleted && !deletedPaths[deletePath] {
			b = helpers.RemoveFromXPath(b, deletePath)
			deletedPaths[deletePath] = true
		}
	}
	if !state.EncapsulationSourceAddressOption.IsNull() && data.EncapsulationSourceAddressOption.IsNull() {
		deletePath := state.getXPath() + "/encapsulation/source-address/option"
		// Check if a parent path is already marked for deletion
		parentAlreadyDeleted := false
		for dp := range deletedPaths {
			if strings.HasPrefix(deletePath, dp+"/") {
				parentAlreadyDeleted = true
				break
			}
		}
		if !parentAlreadyDeleted && !deletedPaths[deletePath] {
			b = helpers.RemoveFromXPath(b, deletePath)
			deletedPaths[deletePath] = true
		}
	}
	if !state.EncapsulationSourceAddress.IsNull() && data.EncapsulationSourceAddress.IsNull() {
		deletePath := state.getXPath() + "/encapsulation/source-address"
		// Check if a parent path is already marked for deletion
		parentAlreadyDeleted := false
		for dp := range deletedPaths {
			if strings.HasPrefix(deletePath, dp+"/") {
				parentAlreadyDeleted = true
				break
			}
		}
		if !parentAlreadyDeleted && !deletedPaths[deletePath] {
			b = helpers.RemoveFromXPath(b, deletePath)
			deletedPaths[deletePath] = true
		}
	}
	if !state.EncapsulationHopLimitValue.IsNull() && data.EncapsulationHopLimitValue.IsNull() {
		deletePath := state.getXPath() + "/encapsulation/hop-limit/value"
		// Check if a parent path is already marked for deletion
		parentAlreadyDeleted := false
		for dp := range deletedPaths {
			if strings.HasPrefix(deletePath, dp+"/") {
				parentAlreadyDeleted = true
				break
			}
		}
		if !parentAlreadyDeleted && !deletedPaths[deletePath] {
			b = helpers.RemoveFromXPath(b, deletePath)
			deletedPaths[deletePath] = true
		}
	}
	if !state.EncapsulationHopLimitOption.IsNull() && data.EncapsulationHopLimitOption.IsNull() {
		deletePath := state.getXPath() + "/encapsulation/hop-limit/option"
		// Check if a parent path is already marked for deletion
		parentAlreadyDeleted := false
		for dp := range deletedPaths {
			if strings.HasPrefix(deletePath, dp+"/") {
				parentAlreadyDeleted = true
				break
			}
		}
		if !parentAlreadyDeleted && !deletedPaths[deletePath] {
			b = helpers.RemoveFromXPath(b, deletePath)
			deletedPaths[deletePath] = true
		}
	}
	if !state.EncapsulationTrafficClassValue.IsNull() && data.EncapsulationTrafficClassValue.IsNull() {
		deletePath := state.getXPath() + "/encapsulation/traffic-class/value"
		// Check if a parent path is already marked for deletion
		parentAlreadyDeleted := false
		for dp := range deletedPaths {
			if strings.HasPrefix(deletePath, dp+"/") {
				parentAlreadyDeleted = true
				break
			}
		}
		if !parentAlreadyDeleted && !deletedPaths[deletePath] {
			b = helpers.RemoveFromXPath(b, deletePath)
			deletedPaths[deletePath] = true
		}
	}
	if !state.EncapsulationTrafficClassOption.IsNull() && data.EncapsulationTrafficClassOption.IsNull() {
		deletePath := state.getXPath() + "/encapsulation/traffic-class/option"
		// Check if a parent path is already marked for deletion
		parentAlreadyDeleted := false
		for dp := range deletedPaths {
			if strings.HasPrefix(deletePath, dp+"/") {
				parentAlreadyDeleted = true
				break
			}
		}
		if !parentAlreadyDeleted && !deletedPaths[deletePath] {
			b = helpers.RemoveFromXPath(b, deletePath)
			deletedPaths[deletePath] = true
		}
	}
	for i := range state.Locators {
		stateKeys := [...]string{"name"}
		stateKeyValues := [...]string{state.Locators[i].Name.ValueString()}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Locators[i].Name.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Locators {
			found = true
			if state.Locators[i].Name.ValueString() != data.Locators[j].Name.ValueString() {
				found = false
			}
			if found {
				if !state.Locators[i].Algorithm.IsNull() && data.Locators[j].Algorithm.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/locators/locators/locator%v/algorithm", predicates))
				}
				// For boolean fields, only delete if state was true (presence container was set)
				if !state.Locators[i].Anycast.IsNull() && state.Locators[i].Anycast.ValueBool() && data.Locators[j].Anycast.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/locators/locators/locator%v/anycast", predicates))
				}
				if !state.Locators[i].PrefixLength.IsNull() && data.Locators[j].PrefixLength.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/locators/locators/locator%v/prefix/prefix-length", predicates))
				}
				if !state.Locators[i].Prefix.IsNull() && data.Locators[j].Prefix.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/locators/locators/locator%v/prefix/prefix", predicates))
				}
				if !state.Locators[i].MicroSegmentBehavior.IsNull() && data.Locators[j].MicroSegmentBehavior.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/locators/locators/locator%v/micro-segment/behavior", predicates))
				}
				// For boolean fields, only delete if state was true (presence container was set)
				if !state.Locators[i].LocatorEnable.IsNull() && state.Locators[i].LocatorEnable.ValueBool() && data.Locators[j].LocatorEnable.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/locators/locators/locator%v/locator-enable", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/locators/locators/locator%v", predicates))
		}
	}
	for i := range state.Formats {
		stateKeys := [...]string{"name"}
		stateKeyValues := [...]string{state.Formats[i].Name.ValueString()}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Formats[i].Name.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Formats {
			found = true
			if state.Formats[i].Name.ValueString() != data.Formats[j].Name.ValueString() {
				found = false
			}
			if found {
				if !state.Formats[i].UsidWideLocalIdBlockExplicitRange.IsNull() && data.Formats[j].UsidWideLocalIdBlockExplicitRange.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/formats/formats/format%v/usid/wide-local-id-block-explicit-range", predicates))
				}
				if !state.Formats[i].UsidLocalIdBlockRangesExplictLibStart.IsNull() && data.Formats[j].UsidLocalIdBlockRangesExplictLibStart.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/formats/formats/format%v/usid/local-id-block-ranges/explict-lib-start", predicates))
				}
				if !state.Formats[i].UsidLocalIdBlockRangesLibStart.IsNull() && data.Formats[j].UsidLocalIdBlockRangesLibStart.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/formats/formats/format%v/usid/local-id-block-ranges/lib-start", predicates))
				}
				// For boolean fields, only delete if state was true (presence container was set)
				if !state.Formats[i].FormatEnable.IsNull() && state.Formats[i].FormatEnable.ValueBool() && data.Formats[j].FormatEnable.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/formats/formats/format%v/format-enable", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/formats/formats/format%v", predicates))
		}
	}
	// For boolean fields, only delete if state was true (presence container was set)
	if !state.LoggingLocatorStatus.IsNull() && state.LoggingLocatorStatus.ValueBool() && data.LoggingLocatorStatus.IsNull() {
		deletePath := state.getXPath() + "/logging/locator-status"
		// Check if a parent path is already marked for deletion
		parentAlreadyDeleted := false
		for dp := range deletedPaths {
			if strings.HasPrefix(deletePath, dp+"/") {
				parentAlreadyDeleted = true
				break
			}
		}
		if !parentAlreadyDeleted && !deletedPaths[deletePath] {
			b = helpers.RemoveFromXPath(b, deletePath)
			deletedPaths[deletePath] = true
		}
	}
	if !state.SidHoldtime.IsNull() && data.SidHoldtime.IsNull() {
		deletePath := state.getXPath() + "/sid-holdtime"
		// Check if a parent path is already marked for deletion
		parentAlreadyDeleted := false
		for dp := range deletedPaths {
			if strings.HasPrefix(deletePath, dp+"/") {
				parentAlreadyDeleted = true
				break
			}
		}
		if !parentAlreadyDeleted && !deletedPaths[deletePath] {
			b = helpers.RemoveFromXPath(b, deletePath)
			deletedPaths[deletePath] = true
		}
	}
	// For boolean fields, only delete if state was true (presence container was set)
	if !state.Enable.IsNull() && state.Enable.ValueBool() && data.Enable.IsNull() {
		deletePath := state.getXPath() + "/enable"
		// Check if a parent path is already marked for deletion
		parentAlreadyDeleted := false
		for dp := range deletedPaths {
			if strings.HasPrefix(deletePath, dp+"/") {
				parentAlreadyDeleted = true
				break
			}
		}
		if !parentAlreadyDeleted && !deletedPaths[deletePath] {
			b = helpers.RemoveFromXPath(b, deletePath)
			deletedPaths[deletePath] = true
		}
	}

	//b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *SegmentRoutingV6) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.EncapsulationSourceAddressAddress.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/encapsulation/source-address/address")
	}
	if !data.EncapsulationSourceAddressOption.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/encapsulation/source-address/option")
	}
	if !data.EncapsulationSourceAddress.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/encapsulation/source-address")
	}
	if !data.EncapsulationHopLimitValue.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/encapsulation/hop-limit/value")
	}
	if !data.EncapsulationHopLimitOption.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/encapsulation/hop-limit/option")
	}
	if !data.EncapsulationTrafficClassValue.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/encapsulation/traffic-class/value")
	}
	if !data.EncapsulationTrafficClassOption.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/encapsulation/traffic-class/option")
	}
	for i := range data.Locators {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Locators[i].Name.ValueString()}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/locators/locators/locator%v", predicates))
	}
	for i := range data.Formats {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Formats[i].Name.ValueString()}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/formats/formats/format%v", predicates))
	}
	if !data.LoggingLocatorStatus.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/logging/locator-status")
	}
	if !data.SidHoldtime.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/sid-holdtime")
	}
	if !data.Enable.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/enable")
	}

	return b.Res()
}

// End of section. //template:end addDeletePathsXML
