// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type PerformanceMeasurementInterface struct {
	Device                          types.String `tfsdk:"device"`
	Id                              types.String `tfsdk:"id"`
	DeleteMode                      types.String `tfsdk:"delete_mode"`
	InterfaceName                   types.String `tfsdk:"interface_name"`
	DelayMeasurement                types.Bool   `tfsdk:"delay_measurement"`
	DelayMeasurementFallback        types.Bool   `tfsdk:"delay_measurement_fallback"`
	DelayMeasurementAdvertiseDelay  types.Int64  `tfsdk:"delay_measurement_advertise_delay"`
	DelayMeasurementProfileName     types.String `tfsdk:"delay_measurement_profile_name"`
	DelayMeasurementStaticDelay     types.Int64  `tfsdk:"delay_measurement_static_delay"`
	NextHopIpv4                     types.String `tfsdk:"next_hop_ipv4"`
	NextHopIpv6                     types.String `tfsdk:"next_hop_ipv6"`
	PathTracing                     types.Bool   `tfsdk:"path_tracing"`
	PathTracingInterfaceId          types.Int64  `tfsdk:"path_tracing_interface_id"`
	PathTracingTimestampTemplateSt0 types.Bool   `tfsdk:"path_tracing_timestamp_template_st0"`
	PathTracingTimestampTemplateSt1 types.Bool   `tfsdk:"path_tracing_timestamp_template_st1"`
	PathTracingTimestampTemplateSt2 types.Bool   `tfsdk:"path_tracing_timestamp_template_st2"`
	PathTracingTimestampTemplateSt3 types.Bool   `tfsdk:"path_tracing_timestamp_template_st3"`
}

type PerformanceMeasurementInterfaceData struct {
	Device                          types.String `tfsdk:"device"`
	Id                              types.String `tfsdk:"id"`
	InterfaceName                   types.String `tfsdk:"interface_name"`
	DelayMeasurement                types.Bool   `tfsdk:"delay_measurement"`
	DelayMeasurementFallback        types.Bool   `tfsdk:"delay_measurement_fallback"`
	DelayMeasurementAdvertiseDelay  types.Int64  `tfsdk:"delay_measurement_advertise_delay"`
	DelayMeasurementProfileName     types.String `tfsdk:"delay_measurement_profile_name"`
	DelayMeasurementStaticDelay     types.Int64  `tfsdk:"delay_measurement_static_delay"`
	NextHopIpv4                     types.String `tfsdk:"next_hop_ipv4"`
	NextHopIpv6                     types.String `tfsdk:"next_hop_ipv6"`
	PathTracing                     types.Bool   `tfsdk:"path_tracing"`
	PathTracingInterfaceId          types.Int64  `tfsdk:"path_tracing_interface_id"`
	PathTracingTimestampTemplateSt0 types.Bool   `tfsdk:"path_tracing_timestamp_template_st0"`
	PathTracingTimestampTemplateSt1 types.Bool   `tfsdk:"path_tracing_timestamp_template_st1"`
	PathTracingTimestampTemplateSt2 types.Bool   `tfsdk:"path_tracing_timestamp_template_st2"`
	PathTracingTimestampTemplateSt3 types.Bool   `tfsdk:"path_tracing_timestamp_template_st3"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data PerformanceMeasurementInterface) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XR-um-performance-measurement-cfg:/performance-measurement/interfaces/interface[interface-name=%s]", data.InterfaceName.ValueString())
}

func (data PerformanceMeasurementInterfaceData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XR-um-performance-measurement-cfg:/performance-measurement/interfaces/interface[interface-name=%s]", data.InterfaceName.ValueString())
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data PerformanceMeasurementInterface) toBody(ctx context.Context) string {
	body := "{}"
	if !data.InterfaceName.IsNull() && !data.InterfaceName.IsUnknown() {
		body, _ = sjson.Set(body, "interface-name", data.InterfaceName.ValueString())
	}
	if !data.DelayMeasurement.IsNull() && !data.DelayMeasurement.IsUnknown() {
		if data.DelayMeasurement.ValueBool() {
			body, _ = sjson.Set(body, "delay-measurement", map[string]string{})
		}
	}
	if !data.DelayMeasurementFallback.IsNull() && !data.DelayMeasurementFallback.IsUnknown() {
		if data.DelayMeasurementFallback.ValueBool() {
			body, _ = sjson.Set(body, "delay-measurement.fallback", map[string]string{})
		}
	}
	if !data.DelayMeasurementAdvertiseDelay.IsNull() && !data.DelayMeasurementAdvertiseDelay.IsUnknown() {
		body, _ = sjson.Set(body, "delay-measurement.advertise-delay", strconv.FormatInt(data.DelayMeasurementAdvertiseDelay.ValueInt64(), 10))
	}
	if !data.DelayMeasurementProfileName.IsNull() && !data.DelayMeasurementProfileName.IsUnknown() {
		body, _ = sjson.Set(body, "delay-measurement.delay-profile.name", data.DelayMeasurementProfileName.ValueString())
	}
	if !data.DelayMeasurementStaticDelay.IsNull() && !data.DelayMeasurementStaticDelay.IsUnknown() {
		body, _ = sjson.Set(body, "delay-measurement.static-delay", strconv.FormatInt(data.DelayMeasurementStaticDelay.ValueInt64(), 10))
	}
	if !data.NextHopIpv4.IsNull() && !data.NextHopIpv4.IsUnknown() {
		body, _ = sjson.Set(body, "next-hop.ipv4", data.NextHopIpv4.ValueString())
	}
	if !data.NextHopIpv6.IsNull() && !data.NextHopIpv6.IsUnknown() {
		body, _ = sjson.Set(body, "next-hop.ipv6", data.NextHopIpv6.ValueString())
	}
	if !data.PathTracing.IsNull() && !data.PathTracing.IsUnknown() {
		if data.PathTracing.ValueBool() {
			body, _ = sjson.Set(body, "path-tracing", map[string]string{})
		}
	}
	if !data.PathTracingInterfaceId.IsNull() && !data.PathTracingInterfaceId.IsUnknown() {
		body, _ = sjson.Set(body, "path-tracing.interface-id", strconv.FormatInt(data.PathTracingInterfaceId.ValueInt64(), 10))
	}
	if !data.PathTracingTimestampTemplateSt0.IsNull() && !data.PathTracingTimestampTemplateSt0.IsUnknown() {
		if data.PathTracingTimestampTemplateSt0.ValueBool() {
			body, _ = sjson.Set(body, "path-tracing.timestamp.template.st0", map[string]string{})
		}
	}
	if !data.PathTracingTimestampTemplateSt1.IsNull() && !data.PathTracingTimestampTemplateSt1.IsUnknown() {
		if data.PathTracingTimestampTemplateSt1.ValueBool() {
			body, _ = sjson.Set(body, "path-tracing.timestamp.template.st1", map[string]string{})
		}
	}
	if !data.PathTracingTimestampTemplateSt2.IsNull() && !data.PathTracingTimestampTemplateSt2.IsUnknown() {
		if data.PathTracingTimestampTemplateSt2.ValueBool() {
			body, _ = sjson.Set(body, "path-tracing.timestamp.template.st2", map[string]string{})
		}
	}
	if !data.PathTracingTimestampTemplateSt3.IsNull() && !data.PathTracingTimestampTemplateSt3.IsUnknown() {
		if data.PathTracingTimestampTemplateSt3.ValueBool() {
			body, _ = sjson.Set(body, "path-tracing.timestamp.template.st3", map[string]string{})
		}
	}
	return body
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody

func (data *PerformanceMeasurementInterface) updateFromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "delay-measurement"); !data.DelayMeasurement.IsNull() {
		if value.Exists() {
			data.DelayMeasurement = types.BoolValue(true)
		} else {
			data.DelayMeasurement = types.BoolValue(false)
		}
	} else {
		data.DelayMeasurement = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "delay-measurement.fallback"); !data.DelayMeasurementFallback.IsNull() {
		if value.Exists() {
			data.DelayMeasurementFallback = types.BoolValue(true)
		} else {
			data.DelayMeasurementFallback = types.BoolValue(false)
		}
	} else {
		data.DelayMeasurementFallback = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "delay-measurement.advertise-delay"); value.Exists() && !data.DelayMeasurementAdvertiseDelay.IsNull() {
		data.DelayMeasurementAdvertiseDelay = types.Int64Value(value.Int())
	} else {
		data.DelayMeasurementAdvertiseDelay = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "delay-measurement.delay-profile.name"); value.Exists() && !data.DelayMeasurementProfileName.IsNull() {
		data.DelayMeasurementProfileName = types.StringValue(value.String())
	} else {
		data.DelayMeasurementProfileName = types.StringNull()
	}
	if value := gjson.GetBytes(res, "delay-measurement.static-delay"); value.Exists() && !data.DelayMeasurementStaticDelay.IsNull() {
		data.DelayMeasurementStaticDelay = types.Int64Value(value.Int())
	} else {
		data.DelayMeasurementStaticDelay = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "next-hop.ipv4"); value.Exists() && !data.NextHopIpv4.IsNull() {
		data.NextHopIpv4 = types.StringValue(value.String())
	} else {
		data.NextHopIpv4 = types.StringNull()
	}
	if value := gjson.GetBytes(res, "next-hop.ipv6"); value.Exists() && !data.NextHopIpv6.IsNull() {
		data.NextHopIpv6 = types.StringValue(value.String())
	} else {
		data.NextHopIpv6 = types.StringNull()
	}
	if value := gjson.GetBytes(res, "path-tracing"); !data.PathTracing.IsNull() {
		if value.Exists() {
			data.PathTracing = types.BoolValue(true)
		} else {
			data.PathTracing = types.BoolValue(false)
		}
	} else {
		data.PathTracing = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "path-tracing.interface-id"); value.Exists() && !data.PathTracingInterfaceId.IsNull() {
		data.PathTracingInterfaceId = types.Int64Value(value.Int())
	} else {
		data.PathTracingInterfaceId = types.Int64Null()
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st0"); !data.PathTracingTimestampTemplateSt0.IsNull() {
		if value.Exists() {
			data.PathTracingTimestampTemplateSt0 = types.BoolValue(true)
		} else {
			data.PathTracingTimestampTemplateSt0 = types.BoolValue(false)
		}
	} else {
		data.PathTracingTimestampTemplateSt0 = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st1"); !data.PathTracingTimestampTemplateSt1.IsNull() {
		if value.Exists() {
			data.PathTracingTimestampTemplateSt1 = types.BoolValue(true)
		} else {
			data.PathTracingTimestampTemplateSt1 = types.BoolValue(false)
		}
	} else {
		data.PathTracingTimestampTemplateSt1 = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st2"); !data.PathTracingTimestampTemplateSt2.IsNull() {
		if value.Exists() {
			data.PathTracingTimestampTemplateSt2 = types.BoolValue(true)
		} else {
			data.PathTracingTimestampTemplateSt2 = types.BoolValue(false)
		}
	} else {
		data.PathTracingTimestampTemplateSt2 = types.BoolNull()
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st3"); !data.PathTracingTimestampTemplateSt3.IsNull() {
		if value.Exists() {
			data.PathTracingTimestampTemplateSt3 = types.BoolValue(true)
		} else {
			data.PathTracingTimestampTemplateSt3 = types.BoolValue(false)
		}
	} else {
		data.PathTracingTimestampTemplateSt3 = types.BoolNull()
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *PerformanceMeasurementInterface) fromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "delay-measurement"); value.Exists() {
		data.DelayMeasurement = types.BoolValue(true)
	} else {
		data.DelayMeasurement = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "delay-measurement.fallback"); value.Exists() {
		data.DelayMeasurementFallback = types.BoolValue(true)
	} else {
		data.DelayMeasurementFallback = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "delay-measurement.advertise-delay"); value.Exists() {
		data.DelayMeasurementAdvertiseDelay = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "delay-measurement.delay-profile.name"); value.Exists() {
		data.DelayMeasurementProfileName = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "delay-measurement.static-delay"); value.Exists() {
		data.DelayMeasurementStaticDelay = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "next-hop.ipv4"); value.Exists() {
		data.NextHopIpv4 = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "next-hop.ipv6"); value.Exists() {
		data.NextHopIpv6 = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "path-tracing"); value.Exists() {
		data.PathTracing = types.BoolValue(true)
	} else {
		data.PathTracing = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "path-tracing.interface-id"); value.Exists() {
		data.PathTracingInterfaceId = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st0"); value.Exists() {
		data.PathTracingTimestampTemplateSt0 = types.BoolValue(true)
	} else {
		data.PathTracingTimestampTemplateSt0 = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st1"); value.Exists() {
		data.PathTracingTimestampTemplateSt1 = types.BoolValue(true)
	} else {
		data.PathTracingTimestampTemplateSt1 = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st2"); value.Exists() {
		data.PathTracingTimestampTemplateSt2 = types.BoolValue(true)
	} else {
		data.PathTracingTimestampTemplateSt2 = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st3"); value.Exists() {
		data.PathTracingTimestampTemplateSt3 = types.BoolValue(true)
	} else {
		data.PathTracingTimestampTemplateSt3 = types.BoolValue(false)
	}
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyData

func (data *PerformanceMeasurementInterfaceData) fromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "delay-measurement"); value.Exists() {
		data.DelayMeasurement = types.BoolValue(true)
	} else {
		data.DelayMeasurement = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "delay-measurement.fallback"); value.Exists() {
		data.DelayMeasurementFallback = types.BoolValue(true)
	} else {
		data.DelayMeasurementFallback = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "delay-measurement.advertise-delay"); value.Exists() {
		data.DelayMeasurementAdvertiseDelay = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "delay-measurement.delay-profile.name"); value.Exists() {
		data.DelayMeasurementProfileName = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "delay-measurement.static-delay"); value.Exists() {
		data.DelayMeasurementStaticDelay = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "next-hop.ipv4"); value.Exists() {
		data.NextHopIpv4 = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "next-hop.ipv6"); value.Exists() {
		data.NextHopIpv6 = types.StringValue(value.String())
	}
	if value := gjson.GetBytes(res, "path-tracing"); value.Exists() {
		data.PathTracing = types.BoolValue(true)
	} else {
		data.PathTracing = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "path-tracing.interface-id"); value.Exists() {
		data.PathTracingInterfaceId = types.Int64Value(value.Int())
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st0"); value.Exists() {
		data.PathTracingTimestampTemplateSt0 = types.BoolValue(true)
	} else {
		data.PathTracingTimestampTemplateSt0 = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st1"); value.Exists() {
		data.PathTracingTimestampTemplateSt1 = types.BoolValue(true)
	} else {
		data.PathTracingTimestampTemplateSt1 = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st2"); value.Exists() {
		data.PathTracingTimestampTemplateSt2 = types.BoolValue(true)
	} else {
		data.PathTracingTimestampTemplateSt2 = types.BoolValue(false)
	}
	if value := gjson.GetBytes(res, "path-tracing.timestamp.template.st3"); value.Exists() {
		data.PathTracingTimestampTemplateSt3 = types.BoolValue(true)
	} else {
		data.PathTracingTimestampTemplateSt3 = types.BoolValue(false)
	}
}

// End of section. //template:end fromBodyData

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletedItems

func (data *PerformanceMeasurementInterface) getDeletedItems(ctx context.Context, state PerformanceMeasurementInterface) []string {
	deletedItems := make([]string, 0)
	if !state.PathTracingTimestampTemplateSt3.IsNull() && data.PathTracingTimestampTemplateSt3.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/path-tracing/timestamp/template/st3", state.getPath()))
	}
	if !state.PathTracingTimestampTemplateSt2.IsNull() && data.PathTracingTimestampTemplateSt2.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/path-tracing/timestamp/template/st2", state.getPath()))
	}
	if !state.PathTracingTimestampTemplateSt1.IsNull() && data.PathTracingTimestampTemplateSt1.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/path-tracing/timestamp/template/st1", state.getPath()))
	}
	if !state.PathTracingTimestampTemplateSt0.IsNull() && data.PathTracingTimestampTemplateSt0.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/path-tracing/timestamp/template/st0", state.getPath()))
	}
	if !state.PathTracingInterfaceId.IsNull() && data.PathTracingInterfaceId.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/path-tracing/interface-id", state.getPath()))
	}
	if !state.PathTracing.IsNull() && data.PathTracing.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/path-tracing", state.getPath()))
	}
	if !state.NextHopIpv6.IsNull() && data.NextHopIpv6.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/next-hop/ipv6", state.getPath()))
	}
	if !state.NextHopIpv4.IsNull() && data.NextHopIpv4.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/next-hop/ipv4", state.getPath()))
	}
	if !state.DelayMeasurementStaticDelay.IsNull() && data.DelayMeasurementStaticDelay.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/delay-measurement/static-delay", state.getPath()))
	}
	if !state.DelayMeasurementProfileName.IsNull() && data.DelayMeasurementProfileName.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/delay-measurement/delay-profile/name", state.getPath()))
	}
	if !state.DelayMeasurementAdvertiseDelay.IsNull() && data.DelayMeasurementAdvertiseDelay.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/delay-measurement", state.getPath()))
	}
	if !state.DelayMeasurementFallback.IsNull() && data.DelayMeasurementFallback.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/delay-measurement", state.getPath()))
	}
	if !state.DelayMeasurement.IsNull() && data.DelayMeasurement.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/delay-measurement", state.getPath()))
	}
	return deletedItems
}

// End of section. //template:end getDeletedItems

// Section below is generated&owned by "gen/generator.go". //template:begin getEmptyLeafsDelete

func (data *PerformanceMeasurementInterface) getEmptyLeafsDelete(ctx context.Context) []string {
	emptyLeafsDelete := make([]string, 0)
	if !data.PathTracingTimestampTemplateSt3.IsNull() && !data.PathTracingTimestampTemplateSt3.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/path-tracing/timestamp/template/st3", data.getPath()))
	}
	if !data.PathTracingTimestampTemplateSt2.IsNull() && !data.PathTracingTimestampTemplateSt2.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/path-tracing/timestamp/template/st2", data.getPath()))
	}
	if !data.PathTracingTimestampTemplateSt1.IsNull() && !data.PathTracingTimestampTemplateSt1.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/path-tracing/timestamp/template/st1", data.getPath()))
	}
	if !data.PathTracingTimestampTemplateSt0.IsNull() && !data.PathTracingTimestampTemplateSt0.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/path-tracing/timestamp/template/st0", data.getPath()))
	}
	if !data.PathTracing.IsNull() && !data.PathTracing.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/path-tracing", data.getPath()))
	}
	if !data.DelayMeasurementFallback.IsNull() && !data.DelayMeasurementFallback.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/delay-measurement", data.getPath()))
	}
	if !data.DelayMeasurement.IsNull() && !data.DelayMeasurement.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/delay-measurement", data.getPath()))
	}
	return emptyLeafsDelete
}

// End of section. //template:end getEmptyLeafsDelete

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletePaths

func (data *PerformanceMeasurementInterface) getDeletePaths(ctx context.Context) []string {
	var deletePaths []string
	if !data.PathTracingTimestampTemplateSt3.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/path-tracing/timestamp/template/st3", data.getPath()))
	}
	if !data.PathTracingTimestampTemplateSt2.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/path-tracing/timestamp/template/st2", data.getPath()))
	}
	if !data.PathTracingTimestampTemplateSt1.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/path-tracing/timestamp/template/st1", data.getPath()))
	}
	if !data.PathTracingTimestampTemplateSt0.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/path-tracing/timestamp/template/st0", data.getPath()))
	}
	if !data.PathTracingInterfaceId.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/path-tracing/interface-id", data.getPath()))
	}
	if !data.PathTracing.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/path-tracing", data.getPath()))
	}
	if !data.NextHopIpv6.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/next-hop/ipv6", data.getPath()))
	}
	if !data.NextHopIpv4.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/next-hop/ipv4", data.getPath()))
	}
	if !data.DelayMeasurementStaticDelay.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/delay-measurement/static-delay", data.getPath()))
	}
	if !data.DelayMeasurementProfileName.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/delay-measurement/delay-profile/name", data.getPath()))
	}
	if !data.DelayMeasurementAdvertiseDelay.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/delay-measurement", data.getPath()))
	}
	if !data.DelayMeasurementFallback.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/delay-measurement", data.getPath()))
	}
	if !data.DelayMeasurement.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/delay-measurement", data.getPath()))
	}
	return deletePaths
}

// End of section. //template:end getDeletePaths
