// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type RoutePolicy struct {
	Device          types.String `tfsdk:"device"`
	Id              types.String `tfsdk:"id"`
	RoutePolicyName types.String `tfsdk:"route_policy_name"`
	Rpl             types.String `tfsdk:"rpl"`
}

type RoutePolicyData struct {
	Device          types.String `tfsdk:"device"`
	Id              types.String `tfsdk:"id"`
	RoutePolicyName types.String `tfsdk:"route_policy_name"`
	Rpl             types.String `tfsdk:"rpl"`
}

func (data RoutePolicy) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XR-um-route-policy-cfg:/routing-policy/route-policies/route-policy[route-policy-name=%s]", data.RoutePolicyName.ValueString())
}

func (data RoutePolicyData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XR-um-route-policy-cfg:/routing-policy/route-policies/route-policy[route-policy-name=%s]", data.RoutePolicyName.ValueString())
}

func (data RoutePolicy) toBody(ctx context.Context) string {
	body := "{}"
	if !data.RoutePolicyName.IsNull() && !data.RoutePolicyName.IsUnknown() {
		body, _ = sjson.Set(body, "route-policy-name", data.RoutePolicyName.ValueString())
	}
	if !data.Rpl.IsNull() && !data.Rpl.IsUnknown() {
		body, _ = sjson.Set(body, "rpl-route-policy", data.Rpl.ValueString())
	}
	return body
}

func (data *RoutePolicy) updateFromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "rpl-route-policy"); value.Exists() && !data.Rpl.IsNull() {
		data.Rpl = types.StringValue(value.String())
	} else {
		data.Rpl = types.StringNull()
	}
}

func (data *RoutePolicy) fromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "rpl-route-policy"); value.Exists() {
		data.Rpl = types.StringValue(value.String())
	}
}

func (data *RoutePolicyData) fromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "rpl-route-policy"); value.Exists() {
		data.Rpl = types.StringValue(value.String())
	}
}

func (data *RoutePolicy) getDeletedItems(ctx context.Context, state RoutePolicy) []string {
	deletedItems := make([]string, 0)
	if !state.Rpl.IsNull() && data.Rpl.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/rpl-route-policy", state.getPath()))
	}
	return deletedItems
}

func (data *RoutePolicy) getEmptyLeafsDelete(ctx context.Context) []string {
	emptyLeafsDelete := make([]string, 0)
	return emptyLeafsDelete
}

func (data *RoutePolicy) getDeletePaths(ctx context.Context) []string {
	var deletePaths []string
	if !data.Rpl.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/rpl-route-policy", data.getPath()))
	}
	return deletePaths
}
