// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"strings"

	"github.com/CiscoDevNet/terraform-provider-iosxr/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
	"github.com/tidwall/gjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type BGPASFormat struct {
	Device     types.String `tfsdk:"device"`
	Id         types.String `tfsdk:"id"`
	DeleteMode types.String `tfsdk:"delete_mode"`
	AsFormat   types.String `tfsdk:"as_format"`
}

type BGPASFormatData struct {
	Device   types.String `tfsdk:"device"`
	Id       types.String `tfsdk:"id"`
	AsFormat types.String `tfsdk:"as_format"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data BGPASFormat) getPath() string {
	return "Cisco-IOS-XR-um-router-bgp-cfg:/as-format"
}

func (data BGPASFormatData) getPath() string {
	return "Cisco-IOS-XR-um-router-bgp-cfg:/as-format"
}

// getXPath returns the XPath for NETCONF operations
func (data BGPASFormat) getXPath() string {
	path := "Cisco-IOS-XR-um-router-bgp-cfg:/as-format"
	return path
}

func (data BGPASFormatData) getXPath() string {
	path := "Cisco-IOS-XR-um-router-bgp-cfg:/as-format"
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data BGPASFormat) toBody(ctx context.Context, providerVersion string) string {
	if !data.AsFormat.IsNull() && !data.AsFormat.IsUnknown() {
		return fmt.Sprintf(`"%s"`, data.AsFormat.ValueString())
	}
	return "{}"
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin getVersionConstraints

// GetVersionConstraints returns the version constraints for all fields
func (data BGPASFormat) GetVersionConstraints() []helpers.FieldVersionConstraint {
	constraints := make([]helpers.FieldVersionConstraint, 0)

	if len(constraints) == 0 {
		return nil
	}
	return constraints
}

// End of section. //template:end getVersionConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getRangeConstraints

// GetRangeConstraints returns the version-specific range constraints for integer fields
func (data BGPASFormat) GetRangeConstraints() []helpers.FieldRangeConstraint {
	return nil
}

// End of section. //template:end getRangeConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getEnumConstraints

// GetEnumConstraints returns the version-specific enum constraints for string fields
func (data BGPASFormat) GetEnumConstraints() []helpers.FieldEnumConstraint {
	return nil
}

// End of section. //template:end getEnumConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getStringLengthConstraints

// GetStringLengthConstraints returns the version-specific string length constraints
func (data BGPASFormat) GetStringLengthConstraints() []helpers.FieldStringLengthConstraint {
	return nil
}

// End of section. //template:end getStringLengthConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin getPatternConstraints

// GetPatternConstraints returns the version-specific string pattern constraints
func (data BGPASFormat) GetPatternConstraints() []helpers.FieldPatternConstraint {
	return nil
}

// End of section. //template:end getPatternConstraints

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody
func (data *BGPASFormat) updateFromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.ParseBytes(res); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.AsFormat = types.StringValue(value.String())
	} else if !data.AsFormat.IsNull() {
		// Preserve config-only value not returned by the device.
		data.AsFormat = types.StringValue(data.AsFormat.ValueString())
	} else {
		data.AsFormat = types.StringNull()
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *BGPASFormat) fromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.ParseBytes(res); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.AsFormat = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyData

func (data *BGPASFormatData) fromBody(ctx context.Context, res []byte, version string) {
	if value := gjson.ParseBytes(res); value.Exists() && (value.Type == gjson.String || value.Type == gjson.Number) {
		data.AsFormat = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyData

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletedItems

func (data *BGPASFormat) getDeletedItems(ctx context.Context, state BGPASFormat, version string) []string {
	deletedItems := make([]string, 0)
	if !state.AsFormat.IsNull() && data.AsFormat.IsNull() {
		deletedItems = append(deletedItems, state.getPath())
	}
	return deletedItems
}

// End of section. //template:end getDeletedItems

// Section below is generated&owned by "gen/generator.go". //template:begin getEmptyLeafsDelete

func (data *BGPASFormat) getEmptyLeafsDelete(ctx context.Context, state *BGPASFormat, version string) []string {
	emptyLeafsDelete := make([]string, 0)
	return emptyLeafsDelete
}

// End of section. //template:end getEmptyLeafsDelete

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletePaths
func (data *BGPASFormat) getDeletePaths(ctx context.Context, version string) []string {
	var deletePaths []string
	if !data.AsFormat.IsNull() {
		deletePaths = append(deletePaths, data.getPath())
	}

	return deletePaths
}

// End of section. //template:end getDeletePaths

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data BGPASFormat) toBodyXML(ctx context.Context, stateArg ...*BGPASFormat) string {
	var state *BGPASFormat
	if len(stateArg) > 0 {
		state = stateArg[0]
	}
	// Special case: value goes directly into root element text content
	body := netconf.Body{}
	if !data.AsFormat.IsNull() && !data.AsFormat.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath(), data.AsFormat.ValueString())
	}
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	// Append delete XML for empty bool leafs (false values that need explicit removal)
	for _, deletePath := range data.getEmptyLeafsDelete(ctx, state, "") {
		bodyString += helpers.RemoveFromXPath(netconf.Body{}, deletePath).Res()
	}
	return bodyString
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *BGPASFormat) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/as-format"); value.Exists() && !data.AsFormat.IsNull() {
		data.AsFormat = types.StringValue(value.String())
	} else if data.AsFormat.IsNull() {
		data.AsFormat = types.StringNull()
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *BGPASFormat) fromBodyXML(ctx context.Context, res xmldot.Result) {
	// Special case: single no_augment_config string attribute - value is in root element text content
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()); value.Exists() {
		data.AsFormat = types.StringValue(value.String())
		return
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/as-format"); value.Exists() {
		data.AsFormat = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *BGPASFormatData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	// Special case: single no_augment_config string attribute - value is in root element text content
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()); value.Exists() {
		data.AsFormat = types.StringValue(value.String())
		return
	}
	if value := helpers.GetFromXPath(res, "data/"+data.getXPath()+"/as-format"); value.Exists() {
		data.AsFormat = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *BGPASFormat) addDeletedItemsXML(ctx context.Context, state BGPASFormat, body string) string {
	// Start with an empty body - we'll build up the delete operations
	b := netconf.Body{}
	deletedPaths := make(map[string]bool)
	_ = deletedPaths // Avoid unused variable error when no delete_parent attributes exist
	if !state.AsFormat.IsNull() && data.AsFormat.IsNull() {
		// For no_augment_config leaf with enum values, delete the specific child element (value)
		// Path should be: root-element/<value> where value is the enum value
		deletePath := state.getXPath() + "/" + state.AsFormat.ValueString()
		// Check if a parent path is already marked for deletion
		parentAlreadyDeleted := false
		for dp := range deletedPaths {
			if strings.HasPrefix(deletePath, dp+"/") {
				parentAlreadyDeleted = true
				break
			}
		}
		if !parentAlreadyDeleted && !deletedPaths[deletePath] {
			b = helpers.RemoveFromXPath(b, deletePath)
			deletedPaths[deletePath] = true
		}
	}

	//b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *BGPASFormat) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.AsFormat.IsNull() {
		// For no_augment_config, delete the entire container (not child elements)
		// This is because these use YANG choice/case - you can't delete individual choice values
		deletePath := data.getXPath()
		b = helpers.RemoveFromXPath(b, deletePath)
	}

	return b.Res()
}

// End of section. //template:end addDeletePathsXML
