// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"reflect"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type SNMPServerVRFHost struct {
	Device                    types.String                                 `tfsdk:"device"`
	Id                        types.String                                 `tfsdk:"id"`
	DeleteMode                types.String                                 `tfsdk:"delete_mode"`
	VrfName                   types.String                                 `tfsdk:"vrf_name"`
	Address                   types.String                                 `tfsdk:"address"`
	TrapsUnencryptedStrings   []SNMPServerVRFHostTrapsUnencryptedStrings   `tfsdk:"traps_unencrypted_strings"`
	InformsUnencryptedStrings []SNMPServerVRFHostInformsUnencryptedStrings `tfsdk:"informs_unencrypted_strings"`
}

type SNMPServerVRFHostData struct {
	Device                    types.String                                 `tfsdk:"device"`
	Id                        types.String                                 `tfsdk:"id"`
	VrfName                   types.String                                 `tfsdk:"vrf_name"`
	Address                   types.String                                 `tfsdk:"address"`
	TrapsUnencryptedStrings   []SNMPServerVRFHostTrapsUnencryptedStrings   `tfsdk:"traps_unencrypted_strings"`
	InformsUnencryptedStrings []SNMPServerVRFHostInformsUnencryptedStrings `tfsdk:"informs_unencrypted_strings"`
}
type SNMPServerVRFHostTrapsUnencryptedStrings struct {
	CommunityString        types.String `tfsdk:"community_string"`
	UdpPort                types.String `tfsdk:"udp_port"`
	VersionV2c             types.Bool   `tfsdk:"version_v2c"`
	VersionV3SecurityLevel types.String `tfsdk:"version_v3_security_level"`
}
type SNMPServerVRFHostInformsUnencryptedStrings struct {
	CommunityString        types.String `tfsdk:"community_string"`
	UdpPort                types.String `tfsdk:"udp_port"`
	VersionV2c             types.Bool   `tfsdk:"version_v2c"`
	VersionV3SecurityLevel types.String `tfsdk:"version_v3_security_level"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data SNMPServerVRFHost) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XR-um-snmp-server-cfg:/snmp-server/vrfs/vrf[vrf-name=%s]/hosts/host[address=%s]", data.VrfName.ValueString(), data.Address.ValueString())
}

func (data SNMPServerVRFHostData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XR-um-snmp-server-cfg:/snmp-server/vrfs/vrf[vrf-name=%s]/hosts/host[address=%s]", data.VrfName.ValueString(), data.Address.ValueString())
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data SNMPServerVRFHost) toBody(ctx context.Context) string {
	body := "{}"
	if !data.Address.IsNull() && !data.Address.IsUnknown() {
		body, _ = sjson.Set(body, "address", data.Address.ValueString())
	}
	if len(data.TrapsUnencryptedStrings) > 0 {
		body, _ = sjson.Set(body, "traps.unencrypted.unencrypted-string", []interface{}{})
		for index, item := range data.TrapsUnencryptedStrings {
			if !item.CommunityString.IsNull() && !item.CommunityString.IsUnknown() {
				body, _ = sjson.Set(body, "traps.unencrypted.unencrypted-string"+"."+strconv.Itoa(index)+"."+"community-string", item.CommunityString.ValueString())
			}
			if !item.UdpPort.IsNull() && !item.UdpPort.IsUnknown() {
				body, _ = sjson.Set(body, "traps.unencrypted.unencrypted-string"+"."+strconv.Itoa(index)+"."+"udp-port", item.UdpPort.ValueString())
			}
			if !item.VersionV2c.IsNull() && !item.VersionV2c.IsUnknown() {
				if item.VersionV2c.ValueBool() {
					body, _ = sjson.Set(body, "traps.unencrypted.unencrypted-string"+"."+strconv.Itoa(index)+"."+"version.v2c", map[string]string{})
				}
			}
			if !item.VersionV3SecurityLevel.IsNull() && !item.VersionV3SecurityLevel.IsUnknown() {
				body, _ = sjson.Set(body, "traps.unencrypted.unencrypted-string"+"."+strconv.Itoa(index)+"."+"version.v3.security-level", item.VersionV3SecurityLevel.ValueString())
			}
		}
	}
	if len(data.InformsUnencryptedStrings) > 0 {
		body, _ = sjson.Set(body, "informs.unencrypted.unencrypted-string", []interface{}{})
		for index, item := range data.InformsUnencryptedStrings {
			if !item.CommunityString.IsNull() && !item.CommunityString.IsUnknown() {
				body, _ = sjson.Set(body, "informs.unencrypted.unencrypted-string"+"."+strconv.Itoa(index)+"."+"community-string", item.CommunityString.ValueString())
			}
			if !item.UdpPort.IsNull() && !item.UdpPort.IsUnknown() {
				body, _ = sjson.Set(body, "informs.unencrypted.unencrypted-string"+"."+strconv.Itoa(index)+"."+"udp-port", item.UdpPort.ValueString())
			}
			if !item.VersionV2c.IsNull() && !item.VersionV2c.IsUnknown() {
				if item.VersionV2c.ValueBool() {
					body, _ = sjson.Set(body, "informs.unencrypted.unencrypted-string"+"."+strconv.Itoa(index)+"."+"version.v2c", map[string]string{})
				}
			}
			if !item.VersionV3SecurityLevel.IsNull() && !item.VersionV3SecurityLevel.IsUnknown() {
				body, _ = sjson.Set(body, "informs.unencrypted.unencrypted-string"+"."+strconv.Itoa(index)+"."+"version.v3.security-level", item.VersionV3SecurityLevel.ValueString())
			}
		}
	}
	return body
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody

func (data *SNMPServerVRFHost) updateFromBody(ctx context.Context, res []byte) {
	for i := range data.TrapsUnencryptedStrings {
		keys := [...]string{"community-string"}
		keyValues := [...]string{data.TrapsUnencryptedStrings[i].CommunityString.ValueString()}

		var r gjson.Result
		gjson.GetBytes(res, "traps.unencrypted.unencrypted-string").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("udp-port"); value.Exists() && !data.TrapsUnencryptedStrings[i].UdpPort.IsNull() {
			data.TrapsUnencryptedStrings[i].UdpPort = types.StringValue(value.String())
		} else {
			data.TrapsUnencryptedStrings[i].UdpPort = types.StringNull()
		}
		if value := r.Get("version.v2c"); !data.TrapsUnencryptedStrings[i].VersionV2c.IsNull() {
			if value.Exists() {
				data.TrapsUnencryptedStrings[i].VersionV2c = types.BoolValue(true)
			} else {
				data.TrapsUnencryptedStrings[i].VersionV2c = types.BoolValue(false)
			}
		} else {
			data.TrapsUnencryptedStrings[i].VersionV2c = types.BoolNull()
		}
		if value := r.Get("version.v3.security-level"); value.Exists() && !data.TrapsUnencryptedStrings[i].VersionV3SecurityLevel.IsNull() {
			data.TrapsUnencryptedStrings[i].VersionV3SecurityLevel = types.StringValue(value.String())
		} else {
			data.TrapsUnencryptedStrings[i].VersionV3SecurityLevel = types.StringNull()
		}
	}
	for i := range data.InformsUnencryptedStrings {
		keys := [...]string{"community-string"}
		keyValues := [...]string{data.InformsUnencryptedStrings[i].CommunityString.ValueString()}

		var r gjson.Result
		gjson.GetBytes(res, "informs.unencrypted.unencrypted-string").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("udp-port"); value.Exists() && !data.InformsUnencryptedStrings[i].UdpPort.IsNull() {
			data.InformsUnencryptedStrings[i].UdpPort = types.StringValue(value.String())
		} else {
			data.InformsUnencryptedStrings[i].UdpPort = types.StringNull()
		}
		if value := r.Get("version.v2c"); !data.InformsUnencryptedStrings[i].VersionV2c.IsNull() {
			if value.Exists() {
				data.InformsUnencryptedStrings[i].VersionV2c = types.BoolValue(true)
			} else {
				data.InformsUnencryptedStrings[i].VersionV2c = types.BoolValue(false)
			}
		} else {
			data.InformsUnencryptedStrings[i].VersionV2c = types.BoolNull()
		}
		if value := r.Get("version.v3.security-level"); value.Exists() && !data.InformsUnencryptedStrings[i].VersionV3SecurityLevel.IsNull() {
			data.InformsUnencryptedStrings[i].VersionV3SecurityLevel = types.StringValue(value.String())
		} else {
			data.InformsUnencryptedStrings[i].VersionV3SecurityLevel = types.StringNull()
		}
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *SNMPServerVRFHost) fromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "traps.unencrypted.unencrypted-string"); value.Exists() {
		data.TrapsUnencryptedStrings = make([]SNMPServerVRFHostTrapsUnencryptedStrings, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := SNMPServerVRFHostTrapsUnencryptedStrings{}
			if cValue := v.Get("udp-port"); cValue.Exists() {
				item.UdpPort = types.StringValue(cValue.String())
			}
			if cValue := v.Get("version.v2c"); cValue.Exists() {
				item.VersionV2c = types.BoolValue(true)
			} else {
				item.VersionV2c = types.BoolValue(false)
			}
			if cValue := v.Get("version.v3.security-level"); cValue.Exists() {
				item.VersionV3SecurityLevel = types.StringValue(cValue.String())
			}
			data.TrapsUnencryptedStrings = append(data.TrapsUnencryptedStrings, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "informs.unencrypted.unencrypted-string"); value.Exists() {
		data.InformsUnencryptedStrings = make([]SNMPServerVRFHostInformsUnencryptedStrings, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := SNMPServerVRFHostInformsUnencryptedStrings{}
			if cValue := v.Get("udp-port"); cValue.Exists() {
				item.UdpPort = types.StringValue(cValue.String())
			}
			if cValue := v.Get("version.v2c"); cValue.Exists() {
				item.VersionV2c = types.BoolValue(true)
			} else {
				item.VersionV2c = types.BoolValue(false)
			}
			if cValue := v.Get("version.v3.security-level"); cValue.Exists() {
				item.VersionV3SecurityLevel = types.StringValue(cValue.String())
			}
			data.InformsUnencryptedStrings = append(data.InformsUnencryptedStrings, item)
			return true
		})
	}
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyData

func (data *SNMPServerVRFHostData) fromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "traps.unencrypted.unencrypted-string"); value.Exists() {
		data.TrapsUnencryptedStrings = make([]SNMPServerVRFHostTrapsUnencryptedStrings, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := SNMPServerVRFHostTrapsUnencryptedStrings{}
			if cValue := v.Get("udp-port"); cValue.Exists() {
				item.UdpPort = types.StringValue(cValue.String())
			}
			if cValue := v.Get("version.v2c"); cValue.Exists() {
				item.VersionV2c = types.BoolValue(true)
			} else {
				item.VersionV2c = types.BoolValue(false)
			}
			if cValue := v.Get("version.v3.security-level"); cValue.Exists() {
				item.VersionV3SecurityLevel = types.StringValue(cValue.String())
			}
			data.TrapsUnencryptedStrings = append(data.TrapsUnencryptedStrings, item)
			return true
		})
	}
	if value := gjson.GetBytes(res, "informs.unencrypted.unencrypted-string"); value.Exists() {
		data.InformsUnencryptedStrings = make([]SNMPServerVRFHostInformsUnencryptedStrings, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := SNMPServerVRFHostInformsUnencryptedStrings{}
			if cValue := v.Get("udp-port"); cValue.Exists() {
				item.UdpPort = types.StringValue(cValue.String())
			}
			if cValue := v.Get("version.v2c"); cValue.Exists() {
				item.VersionV2c = types.BoolValue(true)
			} else {
				item.VersionV2c = types.BoolValue(false)
			}
			if cValue := v.Get("version.v3.security-level"); cValue.Exists() {
				item.VersionV3SecurityLevel = types.StringValue(cValue.String())
			}
			data.InformsUnencryptedStrings = append(data.InformsUnencryptedStrings, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyData

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletedItems

func (data *SNMPServerVRFHost) getDeletedItems(ctx context.Context, state SNMPServerVRFHost) []string {
	deletedItems := make([]string, 0)
	for i := range state.InformsUnencryptedStrings {
		keys := [...]string{"community-string"}
		stateKeyValues := [...]string{state.InformsUnencryptedStrings[i].CommunityString.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + stateKeyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(state.InformsUnencryptedStrings[i].CommunityString.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.InformsUnencryptedStrings {
			found = true
			if state.InformsUnencryptedStrings[i].CommunityString.ValueString() != data.InformsUnencryptedStrings[j].CommunityString.ValueString() {
				found = false
			}
			if found {
				if !state.InformsUnencryptedStrings[i].VersionV3SecurityLevel.IsNull() && data.InformsUnencryptedStrings[j].VersionV3SecurityLevel.IsNull() {
					deletedItems = append(deletedItems, fmt.Sprintf("%v/informs/unencrypted/unencrypted-string%v/version/v3/security-level", state.getPath(), keyString))
				}
				if !state.InformsUnencryptedStrings[i].VersionV2c.IsNull() && data.InformsUnencryptedStrings[j].VersionV2c.IsNull() {
					deletedItems = append(deletedItems, fmt.Sprintf("%v/informs/unencrypted/unencrypted-string%v/version/v2c", state.getPath(), keyString))
				}
				if !state.InformsUnencryptedStrings[i].UdpPort.IsNull() && data.InformsUnencryptedStrings[j].UdpPort.IsNull() {
					deletedItems = append(deletedItems, fmt.Sprintf("%v/informs/unencrypted/unencrypted-string%v/udp-port", state.getPath(), keyString))
				}
				break
			}
		}
		if !found {
			deletedItems = append(deletedItems, fmt.Sprintf("%v/informs/unencrypted/unencrypted-string%v", state.getPath(), keyString))
		}
	}
	for i := range state.TrapsUnencryptedStrings {
		keys := [...]string{"community-string"}
		stateKeyValues := [...]string{state.TrapsUnencryptedStrings[i].CommunityString.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + stateKeyValues[ki] + "]"
		}

		emptyKeys := true
		if !reflect.ValueOf(state.TrapsUnencryptedStrings[i].CommunityString.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.TrapsUnencryptedStrings {
			found = true
			if state.TrapsUnencryptedStrings[i].CommunityString.ValueString() != data.TrapsUnencryptedStrings[j].CommunityString.ValueString() {
				found = false
			}
			if found {
				if !state.TrapsUnencryptedStrings[i].VersionV3SecurityLevel.IsNull() && data.TrapsUnencryptedStrings[j].VersionV3SecurityLevel.IsNull() {
					deletedItems = append(deletedItems, fmt.Sprintf("%v/traps/unencrypted/unencrypted-string%v/version/v3/security-level", state.getPath(), keyString))
				}
				if !state.TrapsUnencryptedStrings[i].VersionV2c.IsNull() && data.TrapsUnencryptedStrings[j].VersionV2c.IsNull() {
					deletedItems = append(deletedItems, fmt.Sprintf("%v/traps/unencrypted/unencrypted-string%v/version/v2c", state.getPath(), keyString))
				}
				if !state.TrapsUnencryptedStrings[i].UdpPort.IsNull() && data.TrapsUnencryptedStrings[j].UdpPort.IsNull() {
					deletedItems = append(deletedItems, fmt.Sprintf("%v/traps/unencrypted/unencrypted-string%v/udp-port", state.getPath(), keyString))
				}
				break
			}
		}
		if !found {
			deletedItems = append(deletedItems, fmt.Sprintf("%v/traps/unencrypted/unencrypted-string%v", state.getPath(), keyString))
		}
	}
	return deletedItems
}

// End of section. //template:end getDeletedItems

// Section below is generated&owned by "gen/generator.go". //template:begin getEmptyLeafsDelete

func (data *SNMPServerVRFHost) getEmptyLeafsDelete(ctx context.Context) []string {
	emptyLeafsDelete := make([]string, 0)
	for i := range data.InformsUnencryptedStrings {
		keys := [...]string{"community-string"}
		keyValues := [...]string{data.InformsUnencryptedStrings[i].CommunityString.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
		if !data.InformsUnencryptedStrings[i].VersionV2c.IsNull() && !data.InformsUnencryptedStrings[i].VersionV2c.ValueBool() {
			emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/informs/unencrypted/unencrypted-string%v/version/v2c", data.getPath(), keyString))
		}
	}
	for i := range data.TrapsUnencryptedStrings {
		keys := [...]string{"community-string"}
		keyValues := [...]string{data.TrapsUnencryptedStrings[i].CommunityString.ValueString()}
		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
		if !data.TrapsUnencryptedStrings[i].VersionV2c.IsNull() && !data.TrapsUnencryptedStrings[i].VersionV2c.ValueBool() {
			emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/traps/unencrypted/unencrypted-string%v/version/v2c", data.getPath(), keyString))
		}
	}
	return emptyLeafsDelete
}

// End of section. //template:end getEmptyLeafsDelete

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletePaths

func (data *SNMPServerVRFHost) getDeletePaths(ctx context.Context) []string {
	var deletePaths []string
	for i := range data.InformsUnencryptedStrings {
		keys := [...]string{"community-string"}
		keyValues := [...]string{data.InformsUnencryptedStrings[i].CommunityString.ValueString()}

		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
		deletePaths = append(deletePaths, fmt.Sprintf("%v/informs/unencrypted/unencrypted-string%v", data.getPath(), keyString))
	}
	for i := range data.TrapsUnencryptedStrings {
		keys := [...]string{"community-string"}
		keyValues := [...]string{data.TrapsUnencryptedStrings[i].CommunityString.ValueString()}

		keyString := ""
		for ki := range keys {
			keyString += "[" + keys[ki] + "=" + keyValues[ki] + "]"
		}
		deletePaths = append(deletePaths, fmt.Sprintf("%v/traps/unencrypted/unencrypted-string%v", data.getPath(), keyString))
	}
	return deletePaths
}

// End of section. //template:end getDeletePaths
