// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type RoutePolicy struct {
	Device          types.String `tfsdk:"device"`
	Id              types.String `tfsdk:"id"`
	RoutePolicyName types.String `tfsdk:"route_policy_name"`
	Rpl             types.String `tfsdk:"rpl"`
}

func (data RoutePolicy) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XR-um-route-policy-cfg:/routing-policy/route-policies/route-policy[route-policy-name=%s]", data.RoutePolicyName.ValueString())
}

func (data RoutePolicy) toBody(ctx context.Context) string {
	body := "{}"
	if !data.RoutePolicyName.IsNull() && !data.RoutePolicyName.IsUnknown() {
		body, _ = sjson.Set(body, "route-policy-name", data.RoutePolicyName.ValueString())
	}
	if !data.Rpl.IsNull() && !data.Rpl.IsUnknown() {
		body, _ = sjson.Set(body, "rpl-route-policy", data.Rpl.ValueString())
	}
	return body
}

func (data *RoutePolicy) updateFromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "rpl-route-policy"); value.Exists() && !data.Rpl.IsNull() {
		data.Rpl = types.StringValue(value.String())
	} else {
		data.Rpl = types.StringNull()
	}
}

func (data *RoutePolicy) fromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "rpl-route-policy"); value.Exists() {
		data.Rpl = types.StringValue(value.String())
	}
}

func (data *RoutePolicy) fromPlan(ctx context.Context, plan RoutePolicy) {
	data.Device = plan.Device
	data.RoutePolicyName = types.StringValue(plan.RoutePolicyName.ValueString())
}

func (data *RoutePolicy) getDeletedListItems(ctx context.Context, state RoutePolicy) []string {
	deletedListItems := make([]string, 0)
	return deletedListItems
}

func (data *RoutePolicy) getEmptyLeafsDelete(ctx context.Context) []string {
	emptyLeafsDelete := make([]string, 0)
	return emptyLeafsDelete
}
