// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type RadiusSourceInterface struct {
	Device          types.String `tfsdk:"device"`
	Id              types.String `tfsdk:"id"`
	Vrf             types.String `tfsdk:"vrf"`
	SourceInterface types.String `tfsdk:"source_interface"`
}

type RadiusSourceInterfaceData struct {
	Device          types.String `tfsdk:"device"`
	Id              types.String `tfsdk:"id"`
	Vrf             types.String `tfsdk:"vrf"`
	SourceInterface types.String `tfsdk:"source_interface"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data RadiusSourceInterface) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XR-um-aaa-cfg:/aaa/Cisco-IOS-XR-um-aaa-radius-server-cfg:radius/vrfs/vrf[vrf-name=%s]", data.Vrf.ValueString())
}

func (data RadiusSourceInterfaceData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XR-um-aaa-cfg:/aaa/Cisco-IOS-XR-um-aaa-radius-server-cfg:radius/vrfs/vrf[vrf-name=%s]", data.Vrf.ValueString())
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data RadiusSourceInterface) toBody(ctx context.Context) string {
	body := "{}"
	if !data.Vrf.IsNull() && !data.Vrf.IsUnknown() {
		body, _ = sjson.Set(body, "vrf-name", data.Vrf.ValueString())
	}
	if !data.SourceInterface.IsNull() && !data.SourceInterface.IsUnknown() {
		body, _ = sjson.Set(body, "source-interface", data.SourceInterface.ValueString())
	}
	return body
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody

func (data *RadiusSourceInterface) updateFromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "source-interface"); value.Exists() && !data.SourceInterface.IsNull() {
		data.SourceInterface = types.StringValue(value.String())
	} else {
		data.SourceInterface = types.StringNull()
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *RadiusSourceInterface) fromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "source-interface"); value.Exists() {
		data.SourceInterface = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyData

func (data *RadiusSourceInterfaceData) fromBody(ctx context.Context, res []byte) {
	if value := gjson.GetBytes(res, "source-interface"); value.Exists() {
		data.SourceInterface = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyData

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletedItems

func (data *RadiusSourceInterface) getDeletedItems(ctx context.Context, state RadiusSourceInterface) []string {
	deletedItems := make([]string, 0)
	if !state.SourceInterface.IsNull() && data.SourceInterface.IsNull() {
		deletedItems = append(deletedItems, fmt.Sprintf("%v/source-interface", state.getPath()))
	}
	return deletedItems
}

// End of section. //template:end getDeletedItems

// Section below is generated&owned by "gen/generator.go". //template:begin getEmptyLeafsDelete

func (data *RadiusSourceInterface) getEmptyLeafsDelete(ctx context.Context) []string {
	emptyLeafsDelete := make([]string, 0)
	return emptyLeafsDelete
}

// End of section. //template:end getEmptyLeafsDelete

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletePaths

func (data *RadiusSourceInterface) getDeletePaths(ctx context.Context) []string {
	var deletePaths []string
	if !data.SourceInterface.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/source-interface", data.getPath()))
	}
	return deletePaths
}

// End of section. //template:end getDeletePaths
