// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccIosxrL2VPNXconnectGroup(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxrL2VPNXconnectGroupConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("iosxr_l2vpn_xconnect_group.test", "group_name", "P2P"),
				),
			},
			{
				ResourceName:  "iosxr_l2vpn_xconnect_group.test",
				ImportState:   true,
				ImportStateId: "Cisco-IOS-XR-um-l2vpn-cfg:/l2vpn/xconnect/groups/group[group-name=P2P]",
			},
		},
	})
}

func testAccIosxrL2VPNXconnectGroupConfig_minimum() string {
	return `
	resource "iosxr_l2vpn_xconnect_group" "test" {
		group_name = "P2P"
	}
	`
}

func testAccIosxrL2VPNXconnectGroupConfig_all() string {
	return `
	resource "iosxr_l2vpn_xconnect_group" "test" {
		group_name = "P2P"
	}
	`
}
