// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccIosxrRouterHSRPInterfaceIPv4GroupV2(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("iosxr_router_hsrp_interface_ipv4_group_v2.test", "group_id", "2345"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxr_router_hsrp_interface_ipv4_group_v2.test", "address", "33.33.33.3"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxr_router_hsrp_interface_ipv4_group_v2.test", "address_learn", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxr_router_hsrp_interface_ipv4_group_v2.test", "priority", "133"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxr_router_hsrp_interface_ipv4_group_v2.test", "name", "NAME22"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxr_router_hsrp_interface_ipv4_group_v2.test", "preempt_delay", "3100"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxr_router_hsrp_interface_ipv4_group_v2.test", "bfd_fast_detect_peer_ipv4", "45.45.45.4"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxr_router_hsrp_interface_ipv4_group_v2.test", "track_interfaces.0.track_name", "GigabitEthernet0/0/0/7"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxr_router_hsrp_interface_ipv4_group_v2.test", "track_interfaces.0.priority_decrement", "66"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxr_router_hsrp_interface_ipv4_group_v2.test", "track_objects.0.object_name", "OBJECT2"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxr_router_hsrp_interface_ipv4_group_v2.test", "track_objects.0.priority_decrement", "77"))
	var steps []resource.TestStep
	if os.Getenv("SKIP_MINIMUM_TEST") == "" {
		steps = append(steps, resource.TestStep{
			Config: testAccIosxrRouterHSRPInterfaceIPv4GroupV2Config_minimum(),
		})
	}
	steps = append(steps, resource.TestStep{
		Config: testAccIosxrRouterHSRPInterfaceIPv4GroupV2Config_all(),
		Check:  resource.ComposeTestCheckFunc(checks...),
	})
	steps = append(steps, resource.TestStep{
		ResourceName:  "iosxr_router_hsrp_interface_ipv4_group_v2.test",
		ImportState:   true,
		ImportStateId: "GigabitEthernet0/0/0/1,2345",
		Check:         resource.ComposeTestCheckFunc(checks...),
	})
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps:                    steps,
	})
}

func testAccIosxrRouterHSRPInterfaceIPv4GroupV2Config_minimum() string {
	config := `resource "iosxr_router_hsrp_interface_ipv4_group_v2" "test" {` + "\n"
	config += `	interface_name = "GigabitEthernet0/0/0/1"` + "\n"
	config += `	group_id = 2345` + "\n"
	config += `}` + "\n"
	return config
}

func testAccIosxrRouterHSRPInterfaceIPv4GroupV2Config_all() string {
	config := `resource "iosxr_router_hsrp_interface_ipv4_group_v2" "test" {` + "\n"
	config += `	interface_name = "GigabitEthernet0/0/0/1"` + "\n"
	config += `	group_id = 2345` + "\n"
	config += `	address = "33.33.33.3"` + "\n"
	config += `	address_learn = false` + "\n"
	config += `	priority = 133` + "\n"
	config += `	name = "NAME22"` + "\n"
	config += `	preempt_delay = 3100` + "\n"
	config += `	bfd_fast_detect_peer_ipv4 = "45.45.45.4"` + "\n"
	config += `	track_interfaces = [{` + "\n"
	config += `		track_name = "GigabitEthernet0/0/0/7"` + "\n"
	config += `		priority_decrement = 66` + "\n"
	config += `		}]` + "\n"
	config += `	track_objects = [{` + "\n"
	config += `		object_name = "OBJECT2"` + "\n"
	config += `		priority_decrement = 77` + "\n"
	config += `		}]` + "\n"
	config += `}` + "\n"
	return config
}
